name = "stock-api-worker"
main = "src/index.ts"
compatibility_date = "2024-09-26"
account_id = "7c72ee1bcdc2afa2991960a054a10e8e"

[[d1_databases]]
binding = "DB"
database_name = "stock_db"
database_id = "64fdc9a0-7248-46f6-8da5-578f0a3b8af6"
migrations_dir = "drizzle/migrations"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "stock-contents"
