PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNL_2021_consolidated', 'VNL', 2021, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNL_2015_consolidated', 'VNL', 2015, 'consolidated', 'Công ty TNHH Kiểm toán DTL', 'unqualified', 0, NULL),
('VNI_2025_consolidated', 'VNI', 2025, 'consolidated', 'AASCS', 'qualified', 1, 'Nợ ngắn hạn vượt quá tài sản ngắn hạn 109.026.345.172 VND, khả năng thanh toán bị hạn chế.'),
('VNI_2023_consolidated', 'VNI', 2023, 'consolidated', 'Công ty TNHH Dịch vụ tư vấn Tài chính – Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VNH_2025_consolidated', 'VNH', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Quốc tế', 'qualified', 1, 'Tại ngày 31/12/2025, lỗ lũy kế của Công ty là 73.526.377.517 đồng, chiếm 91,6% vốn chủ sở hữu. Năm 2024, Công ty không phát sinh doanh thu, năm 2025 Công ty có phát sinh doanh thu, nhưng lợi nhuận chủ yếu đến từ việc hoàn nhập các khoản dự phòng. Điều này cho thấy khả năng hoạt động liên tục của Công ty có thể bị ảnh hưởng.'),
('VNI_2024_consolidated', 'VNI', 2024, 'consolidated', 'AASCS', 'qualified', 1, 'Nợ ngắn hạn vượt tài sản ngắn hạn 64.217.456.385 VND, lưu chuyển tiền tệ từ hoạt động kinh doanh âm, và nghi ngờ về khả năng hoạt động liên tục.'),
('VNH_2024_consolidated', 'VNH', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh Hà Nội', 'disclaimer', 1, 'Tại ngày 31/12/2024, lỗ lũy kế của Công ty là 75.710.943.108 đồng. Trong năm 2024, Công ty tạm dừng các hoạt động kinh doanh, không phát sinh doanh thu bán hàng và cung cấp dịch vụ, chỉ phát sinh chi phí thuế môn bài và phí chuyển tiền.'),
('VNH_2023_consolidated', 'VNH', 2023, 'consolidated', 'Chi nhánh Hà Nội - Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNH_2021_consolidated', 'VNH', 2021, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'qualified', 1, 'Lỗ lũy kế của công ty là 76.526.195.494 đồng và nợ ngắn hạn vượt quá tài sản ngắn hạn với số tiền là 4.834.783.141 đồng. Công ty đã bị Cục thuế Thành phố Hồ Chí Minh ra thông báo về việc cưỡng chế hóa đơn không còn giá trị sử dụng do không chấp hành nộp tiền nợ thuế và tiền chậm nộp. Công ty đang hoạt động thương mại cầm chừng.'),
('VNH_2022_consolidated', 'VNH', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'qualified', 1, 'Tại ngày 31/12/2022, lỗ lũy kế của công ty là 76.595.333.039 đồng; một số khoản nợ phải trả quá hạn thanh toán; Công ty đã bị Cục thuế Thành phố Hồ Chí Minh ra thông báo về việc cương chế hóa đơn không còn giá trị sử dụng do không chấp hành nộp tiền nợ thuế và tiền chậm nộp. Các vấn đề này tồn tại các yếu tố không chắc chắn ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VNH_2020_consolidated', 'VNH', 2020, 'consolidated', 'Công ty TNHH Kiểm toán – Tư vấn Đất Việt', 'unqualified', 0, NULL),
('VNH_2019_consolidated', 'VNH', 2019, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'unqualified', 0, NULL),
('VNH_2018_consolidated', 'VNH', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 1, 'Trong năm 2018 Công ty tiếp tục lỗ 1.262.052.983 VND. Đến ngày 31 tháng 12 năm 2018 khoản lỗ lũy kế được ghi nhận là 87.334.899.150 VND. Ngoài ra tại ngày 31 tháng 12 năm 2018 nợ phải trả ngắn hạn lớn hơn tổng tài sản ngắn hạn 8.332.466.341 VND.'),
('VNH_2015_consolidated', 'VNH', 2015, 'consolidated', 'Công ty TNHH Kiểm toán DTL (RSM Vietnam)', 'unqualified', 0, NULL),
('VNH_2017_consolidated', 'VNH', 2017, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 1, 'Năm tài chính kết thúc ngày 31 tháng 12 năm 2017 Công ty tiếp tục lỗ, đến ngày 31 tháng 12 năm 2017 khoản lỗ lũy kế được ghi nhận là 86.072.846.167 đồng. Ngoài ra tại ngày 31 tháng 12 năm 2017 nợ phải trả ngắn hạn lớn hơn tổng tài sản ngắn hạn 4.233.281.319 đồng. Các yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VNH_2016_consolidated', 'VNH', 2016, 'consolidated', 'Công ty TNHH Kiểm toán DFK Việt Nam', 'unqualified', 1, 'Trong năm 2016, Công ty đã tiến hành bán thanh lý hầu như toàn bộ tài sản của Công ty gồm hàng tồn kho và tài sản cố định nhằm thanh toán hết các khoản nợ gốc và lãi vay tại các ngân hàng. Việc này làm gia tăng nghi ngờ về khả năng hoạt động liên tục của Công ty.'),
('VNG_2025_consolidated', 'VNG', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 1, 'Nhóm Công ty chưa ghi nhận khoản nghĩa vụ tiền thuê đất có mặt nước chuyên dùng phát sinh bổ sung với tổng số tiền là 100,71 tỷ đồng, do đang chờ kết luận chính thức của cơ quan Nhà nước có thẩm quyền.'),
('VNG_2025_parent', 'VNG', 2025, 'parent', 'UHY Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VNG_2024_consolidated', 'VNG', 2024, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VNG_2024_parent', 'VNG', 2024, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNG_2022_consolidated', 'VNG', 2022, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2023_parent', 'VNG', 2023, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VNG_2023_consolidated', 'VNG', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2022_parent', 'VNG', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2021_consolidated', 'VNG', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2021_parent', 'VNG', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2020_parent', 'VNG', 2020, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2019_consolidated', 'VNG', 2019, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2020_consolidated', 'VNG', 2020, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2017_parent', 'VNG', 2017, 'parent', 'AASC', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2017, tài sản ngắn hạn nhỏ hơn nợ ngắn hạn khoảng 28 tỷ đồng, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ về khả năng hoạt động liên tục của Công ty.'),
('VNG_2017_consolidated', 'VNG', 2017, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VNG_2019_parent', 'VNG', 2019, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNG_2018_parent', 'VNG', 2018, 'parent', 'AASC Auditing Firm', 'unqualified', 1, 'Tài sản ngắn hạn nhỏ hơn Nợ ngắn hạn 59,4 tỷ đồng, dẫn đến nghi ngờ về khả năng hoạt động liên tục.'),
('VNG_2018_consolidated', 'VNG', 2018, 'consolidated', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VNG_2016_consolidated', 'VNG', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VNG_2016_parent', 'VNG', 2016, 'parent', 'AASC', 'unqualified', 0, NULL),
('VNG_2015_consolidated', 'VNG', 2015, 'consolidated', 'AASC', 'unqualified', 1, 'Để đảm bảo nguồn vốn cho Dự án sửa chữa Khách sạn Golf Cần Thơ, Công ty đã thực hiện vay ngắn hạn các đối tác, dẫn đến chỉ tiêu Nợ phải trả ngắn hạn lớn hơn tài sản ngắn hạn, có dấu hiện không chắc chắn có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty. Tuy nhiên, Tập đoàn Thành Thành Công đã có cam kết tài trợ vốn cho dự án Khách sạn Golf Cần Thơ, do vậy Công ty vẫn đảm bảo khả năng thanh toán trong thời gian tới.'),
('VNG_2015_parent', 'VNG', 2015, 'parent', 'AASC', 'unqualified', 0, NULL),
('VNF_2025_consolidated', 'VNF', 2025, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VNF_2025_parent', 'VNF', 2025, 'parent', 'PwC Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNF_2024_consolidated', 'VNF', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNF_2024_parent', 'VNF', 2024, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNF_2023_consolidated', 'VNF', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNF_2022_consolidated', 'VNF', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNF_2021_consolidated', 'VNF', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNF_2020_consolidated', 'VNF', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VNF_2020_parent', 'VNF', 2020, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VNF_2019_parent', 'VNF', 2019, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VNF_2019_consolidated', 'VNF', 2019, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VNF_2017_parent', 'VNF', 2017, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VNF_2018_consolidated', 'VNF', 2018, 'consolidated', 'A&C Auditing and Consulting Co., Ltd. (Công ty TNHH Kiểm toán và Tư vấn A&C)', 'unqualified', 0, NULL),
('VNF_2017_consolidated', 'VNF', 2017, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VNF_2016_consolidated', 'VNF', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (A&C Auditing and Consulting Co., Ltd.)', 'unqualified', 0, NULL),
('VNF_2015_consolidated', 'VNF', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VNF_2016_parent', 'VNF', 2016, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VNF_2015_parent', 'VNF', 2015, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VND_2024_consolidated', 'VND', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VND_2025_consolidated', 'VND', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VND_2016_consolidated', 'VND', 2016, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VND_2015_consolidated', 'VND', 2015, 'consolidated', 'KPMG Limited', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNC_2025_consolidated', 'VNC', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2024_consolidated', 'VNC', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2023_consolidated', 'VNC', 2023, 'consolidated', 'Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('VNC_2022_consolidated', 'VNC', 2022, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2023_parent', 'VNC', 2023, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2022_parent', 'VNC', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2021_consolidated', 'VNC', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2021_parent', 'VNC', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2020_parent', 'VNC', 2020, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2020_consolidated', 'VNC', 2020, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2019_consolidated', 'VNC', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2019_parent', 'VNC', 2019, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2018_parent', 'VNC', 2018, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2018_consolidated', 'VNC', 2018, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2016_consolidated', 'VNC', 2016, 'consolidated', 'KPMG Limited', 'unqualified', 0, NULL),
('VNC_2017_consolidated', 'VNC', 2017, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VNB_2025_consolidated', 'VNB', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNC_2016_parent', 'VNC', 2016, 'parent', 'KPMG Limited', 'unqualified', 0, NULL),
('VNC_2015_consolidated', 'VNC', 2015, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VNB_2023_consolidated', 'VNB', 2023, 'consolidated', 'Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNC_2015_parent', 'VNC', 2015, 'parent', 'KPMG Limited', 'unqualified', 0, NULL),
('VNB_2024_consolidated', 'VNB', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNB_2022_consolidated', 'VNB', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNB_2020_consolidated', 'VNB', 2020, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VNB_2019_consolidated', 'VNB', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNB_2021_consolidated', 'VNB', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNB_2018_consolidated', 'VNB', 2018, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNB_2016_consolidated', 'VNB', 2016, 'consolidated', 'Ernst & Young Việt Nam', 'qualified', 0, NULL),
('VNB_2017_consolidated', 'VNB', 2017, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'qualified', 0, NULL),
('VNB_2015_consolidated', 'VNB', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'qualified', 0, NULL),
('VNA_2025_consolidated', 'VNA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNA_2025_parent', 'VNA', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNA_2024_parent', 'VNA', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNA_2024_consolidated', 'VNA', 2024, 'consolidated', 'UHY', 'unqualified', 0, NULL),
('VNA_2023_parent', 'VNA', 2023, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNA_2022_parent', 'VNA', 2022, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VNA_2022_consolidated', 'VNA', 2022, 'consolidated', 'AASC AUDITING FIRM', 'unqualified', 0, NULL),
('VNA_2021_parent', 'VNA', 2021, 'parent', 'AASC Auditing Firm', 'unqualified', 1, 'Tại thời điểm ngày 31 tháng 12 năm 2021, Nợ ngắn hạn vượt quá Tài sản ngắn hạn 31,65 tỷ đồng, lỗ lũy kế 41,25 tỷ đồng.'),
('VNA_2021_consolidated', 'VNA', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Tại thời điểm ngày 31/12/2021, nợ ngắn hạn vượt quá tài sản ngắn hạn 26,6 tỷ đồng, lỗ lũy kế 40,65 tỷ đồng. Công ty đang tái cơ cấu nợ theo chỉ đạo của Chính phủ, khả năng trả nợ tùy thuộc vào kết quả quá trình tái cơ cấu.'),
('VMT_2025_consolidated', 'VMT', 2025, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VMT_2024_consolidated', 'VMT', 2024, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMT_2022_consolidated', 'VMT', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMK_2025_consolidated', 'VMK', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn PKF - TTG', 'unqualified', 0, NULL),
('VMT_2021_consolidated', 'VMT', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMK_2023_consolidated', 'VMK', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMK_2022_consolidated', 'VMK', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VNA_2023_consolidated', 'VNA', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2025_consolidated', 'VOS', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2024_consolidated', 'VOS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2023_consolidated', 'VOS', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2022_consolidated', 'VOS', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VOS_2021_consolidated', 'VOS', 2021, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VOS_2019_consolidated', 'VOS', 2019, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2019, nợ ngắn hạn lớn hơn tài sản ngắn hạn 333.493.705.871 VND. Yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VOS_2018_consolidated', 'VOS', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2018, nợ ngắn hạn lớn hơn tài sản ngắn hạn 171.943.246.087 VND. Yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VOS_2017_consolidated', 'VOS', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2017, nợ ngắn hạn lớn hơn tài sản ngắn hạn 197.031.998.507 VND. Yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VOS_2016_consolidated', 'VOS', 2016, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VOS_2025_parent', 'VOS', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2023_parent', 'VOS', 2023, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2021_parent', 'VOS', 2021, 'parent', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VOS_2018_parent', 'VOS', 2018, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2018 nợ ngắn hạn lớn hơn tài sản ngắn hạn 275.765.792.159 VND. Yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VOS_2022_parent', 'VOS', 2022, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VOS_2019_parent', 'VOS', 2019, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2019 nợ ngắn hạn lớn hơn tài sản ngắn hạn 348.213.053.046 VND. Kiểm toán viên lưu ý người đọc về thuyết minh VII.6 về khả năng hoạt động liên tục của Công ty.'),
('VOS_2017_parent', 'VOS', 2017, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2017 nợ ngắn hạn lớn hơn tài sản ngắn hạn 300.535.039.499 VND. Yếu tố này có thể ảnh hưởng đến khả năng hoạt động liên tục của Công ty.'),
('VOS_2016_parent', 'VOS', 2016, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VOS_2024_parent', 'VOS', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VOS_2015_parent', 'VOS', 2015, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VOS_2015_consolidated', 'VOS', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VCB_2025_parent', 'VCB', 2025, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2022_consolidated', 'VCB', 2022, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2025_consolidated', 'VCB', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2023_consolidated', 'VCB', 2023, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VCB_2020_consolidated', 'VCB', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2022_parent', 'VCB', 2022, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2019_consolidated', 'VCB', 2019, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2024_parent', 'VCB', 2024, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2024_consolidated', 'VCB', 2024, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2021_consolidated', 'VCB', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2021_parent', 'VCB', 2021, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2020_parent', 'VCB', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2019_parent', 'VCB', 2019, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VCB_2018_parent', 'VCB', 2018, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2018_consolidated', 'VCB', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2017_parent', 'VCB', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2017_consolidated', 'VCB', 2017, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VCB_2016_parent', 'VCB', 2016, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2016_consolidated', 'VCB', 2016, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2015_consolidated', 'VCB', 2015, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VCB_2015_parent', 'VCB', 2015, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2025_consolidated', 'TCB', 2025, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2025_parent', 'TCB', 2025, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2022_parent', 'TCB', 2022, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2022_consolidated', 'TCB', 2022, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2021_parent', 'TCB', 2021, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2021_consolidated', 'TCB', 2021, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2020_parent', 'TCB', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('TCB_2023_parent', 'TCB', 2023, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2023_consolidated', 'TCB', 2023, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('TCB_2019_consolidated', 'TCB', 2019, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2020_consolidated', 'TCB', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('TCB_2019_parent', 'TCB', 2019, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('TCB_2018_parent', 'TCB', 2018, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2018_consolidated', 'TCB', 2018, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2017_parent', 'TCB', 2017, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('TCB_2017_consolidated', 'TCB', 2017, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2025_consolidated', 'CTG', 2025, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('CTG_2025_parent', 'CTG', 2025, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('CTG_2024_parent', 'CTG', 2024, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2024_consolidated', 'CTG', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2023_consolidated', 'CTG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2023_parent', 'CTG', 2023, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2022_consolidated', 'CTG', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2021_consolidated', 'CTG', 2021, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2022_parent', 'CTG', 2022, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2020_parent', 'CTG', 2020, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2020_consolidated', 'CTG', 2020, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2019_consolidated', 'CTG', 2019, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2019_parent', 'CTG', 2019, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2018_consolidated', 'CTG', 2018, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2018_parent', 'CTG', 2018, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2017_consolidated', 'CTG', 2017, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('CTG_2017_parent', 'CTG', 2017, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('CTG_2016_consolidated', 'CTG', 2016, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2016_parent', 'CTG', 2016, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2015_consolidated', 'CTG', 2015, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('CTG_2015_parent', 'CTG', 2015, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2025_consolidated', 'BID', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2025_parent', 'BID', 2025, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2024_consolidated', 'BID', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('BID_2024_parent', 'BID', 2024, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('BID_2023_consolidated', 'BID', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2023_parent', 'BID', 2023, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2022_consolidated', 'BID', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2021_consolidated', 'BID', 2021, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2022_parent', 'BID', 2022, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2020_parent', 'BID', 2020, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2020_consolidated', 'BID', 2020, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2019_consolidated', 'BID', 2019, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2018_consolidated', 'BID', 2018, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('BID_2018_parent', 'BID', 2018, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('BID_2017_consolidated', 'BID', 2017, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
