PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('YTC_2015_consolidated', 'YTC', 2015, 'consolidated', 'Southern Auditing and Accounting Financial Consulting Services Company Limited (AASCS)', 'unqualified', 0, NULL),
('YSVN_2021_consolidated', 'YSVN', 2021, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YSVN_2020_consolidated', 'YSVN', 2020, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YSVN_2023_consolidated', 'YSVN', 2023, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YSVN_2019_consolidated', 'YSVN', 2019, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YTC_2024_consolidated', 'YTC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('YSVN_2025_consolidated', 'YSVN', 2025, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YTC_2023_consolidated', 'YTC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('YTC_2021_consolidated', 'YTC', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'qualified', 0, NULL),
('YTC_2020_consolidated', 'YTC', 2020, 'consolidated', 'A&C Auditing and Consulting Co., Ltd. (Baker Tilly A&C)', 'qualified', 1, 'Hoạt động kinh doanh bị lỗ 12.013.078.416 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2020 là 40.105.016.544 VND. Ngoài ra, các khoản nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn 41.846.707.219 VND.'),
('YTC_2018_consolidated', 'YTC', 2018, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('YTC_2017_consolidated', 'YTC', 2017, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('YTC_2025_consolidated', 'YTC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('YTC_2016_consolidated', 'YTC', 2016, 'consolidated', 'CÔNG TY TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('YEG_2025_consolidated', 'YEG', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('YEG_2025_parent', 'YEG', 2025, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('YEG_2024_consolidated', 'YEG', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('YEG_2023_parent', 'YEG', 2023, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('YEG_2024_parent', 'YEG', 2024, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('YEG_2023_consolidated', 'YEG', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('YEG_2022_consolidated', 'YEG', 2022, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2021_consolidated', 'YEG', 2021, 'consolidated', 'PwC Vietnam', 'unqualified', 0, NULL),
('YEG_2021_parent', 'YEG', 2021, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2020_parent', 'YEG', 2020, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2020_consolidated', 'YEG', 2020, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2022_parent', 'YEG', 2022, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2018_consolidated', 'YEG', 2018, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2019_parent', 'YEG', 2019, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2017_consolidated', 'YEG', 2017, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2017_parent', 'YEG', 2017, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2018_parent', 'YEG', 2018, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2015_parent', 'YEG', 2015, 'parent', 'PricewaterhouseCoopers Việt Nam', 'unqualified', 0, NULL),
('YEG_2016_parent', 'YEG', 2016, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YEG_2016_consolidated', 'YEG', 2016, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YBM_2025_consolidated', 'YBM', 2025, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 0, NULL),
('YBM_2025_parent', 'YBM', 2025, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 0, NULL),
('YBM_2022_consolidated', 'YBM', 2022, 'consolidated', 'Baker Tilly A&C', 'unqualified', 0, NULL),
('YBM_2021_consolidated', 'YBM', 2021, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('YBM_2020_consolidated', 'YBM', 2020, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('YBM_2021_parent', 'YBM', 2021, 'parent', 'Baker Tilly A&C', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('YBM_2020_parent', 'YBM', 2020, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('YBM_2018_consolidated', 'YBM', 2018, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('YBM_2019_consolidated', 'YBM', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'qualified', 0, NULL),
('YBM_2018_parent', 'YBM', 2018, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('YEG_2019_consolidated', 'YEG', 2019, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('YBM_2019_parent', 'YBM', 2019, 'parent', 'Baker Tilly A&C', 'qualified', 0, NULL),
('YEG_2015_consolidated', 'YEG', 2015, 'consolidated', 'PricewaterhouseCoopers Vietnam', 'unqualified', 0, NULL),
('YBM_2022_parent', 'YBM', 2022, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 0, NULL),
('YBC_2024_consolidated', 'YBC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2024 nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 122.062.672.040 đồng.'),
('YBM_2017_parent', 'YBM', 2017, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('YBC_2020_consolidated', 'YBC', 2020, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2020 khoản lỗ lũy kế của Công ty là 30.144.912.607 đồng chiếm 25,5% vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 253.256.136.160 đồng. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('YBC_2022_consolidated', 'YBC', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2022 khoản lỗ lũy kế của Công ty là 20.570.052.068 đồng chiếm 17,43% vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 185.698.894.745 đồng. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('YBC_2021_consolidated', 'YBC', 2021, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31/12/2021, khoản lỗ lũy kế là 28.078.526.667 đồng chiếm 23,80% vốn chủ sở hữu, nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 190.595.736.428 đồng. Tuy nhiên Công ty vẫn đang có lãi, có chiều hướng phát triển tích cực và tiếp tục được BIDV CN Yên Bái, Agribank CN Yên Bình cho vay. Ban Giám đốc và kiểm toán viên đánh giá giả định hoạt động liên tục vẫn phù hợp.'),
('YBC_2017_consolidated', 'YBC', 2017, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2017 khoản lỗ lũy kế của Công ty là 37.284.536.814 đồng chiếm 63,87% vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 251.632.180.533 đồng. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('YBC_2019_consolidated', 'YBC', 2019, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2019 khoản lỗ lũy kế của Công ty là 31.741.912.229 đồng chiếm 26,9%vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 243.136.114.987 đồng. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty. Ban Giám đốc cho rằng việc lập Báo cáo tài chính theo giả định Hoạt động liên tục vẫn là phù hợp.'),
('YBC_2018_consolidated', 'YBC', 2018, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2018 khoản lỗ lũy kế của Công ty là 33.129.779.373 đồng chiếm 44,5% vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 221.548.755.037 đồng. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('XPH_2024_consolidated', 'XPH', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('XPH_2023_consolidated', 'XPH', 2023, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('XPH_2025_consolidated', 'XPH', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('XPH_2020_consolidated', 'XPH', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('XPH_2021_consolidated', 'XPH', 2021, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'disclaimer', 0, NULL),
('XPH_2022_consolidated', 'XPH', 2022, 'consolidated', 'AASC', 'qualified', 0, NULL),
('XPH_2017_consolidated', 'XPH', 2017, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('XPH_2019_consolidated', 'XPH', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('XPH_2018_consolidated', 'XPH', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('XPH_2015_consolidated', 'XPH', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('XMP_2025_consolidated', 'XMP', 2025, 'consolidated', 'AASC', 'unqualified', 1, 'Khả năng thanh toán của Công ty trong 12 tháng tới phụ thuộc vào tình hình hoạt động kinh doanh thời gian tới cũng như khả năng huy động vốn từ các tổ chức tín dụng.'),
('XMP_2024_consolidated', 'XMP', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('XMP_2022_consolidated', 'XMP', 2022, 'consolidated', 'AASC Auditing Firm', 'unqualified', 1, 'Tài sản ngắn hạn thấp hơn nợ ngắn hạn 22.698.681.542 VND, có nghi ngờ về khả năng hoạt động liên tục.'),
('XMP_2020_consolidated', 'XMP', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('XMD_2025_consolidated', 'XMD', 2025, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán NVA', 'unqualified', 0, NULL),
('XMP_2021_consolidated', 'XMP', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 1, 'Tại 31/12/2021, tài sản ngắn hạn của Công ty đang thấp hơn nợ ngắn hạn với số tiền là 18.565.823.205 VND dẫn đến quan ngại về khả năng thanh toán cho các khoản nợ đến hạn.'),
('XMD_2022_consolidated', 'XMD', 2022, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMD_2023_consolidated', 'XMD', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('XMD_2020_consolidated', 'XMD', 2020, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMD_2021_consolidated', 'XMD', 2021, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('XMD_2019_consolidated', 'XMD', 2019, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('XMD_2017_consolidated', 'XMD', 2017, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMD_2018_consolidated', 'XMD', 2018, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMC_2025_parent', 'XMC', 2025, 'parent', 'Chi nhánh Công ty TNHH Kiểm toán NVA', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('XMC_2025_consolidated', 'XMC', 2025, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán NVA', 'unqualified', 0, NULL),
('XMC_2024_consolidated', 'XMC', 2024, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán NVA', 'unqualified', 0, NULL),
('XMD_2024_consolidated', 'XMD', 2024, 'consolidated', 'Công ty TNHH Kiểm toán NVA', 'unqualified', 0, NULL),
('XMC_2022_parent', 'XMC', 2022, 'parent', 'Nam Việt Auditing and Accounting Financial Consulting Services Co., Ltd. (AASCN)', 'unqualified', 0, NULL),
('XMC_2023_consolidated', 'XMC', 2023, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt', 'unqualified', 0, NULL),
('XMC_2022_consolidated', 'XMC', 2022, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN) - Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('XMC_2021_consolidated', 'XMC', 2021, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt', 'unqualified', 0, NULL),
('XMC_2020_consolidated', 'XMC', 2020, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMC_2020_parent', 'XMC', 2020, 'parent', 'Nam Viet Auditing and Accounting Financial Consulting Services Co., Ltd (AASCN)', 'unqualified', 0, NULL),
('XMC_2019_consolidated', 'XMC', 2019, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('XMC_2018_consolidated', 'XMC', 2018, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMC_2018_parent', 'XMC', 2018, 'parent', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt Nam (AASCN)', 'unqualified', 0, NULL),
('YBC_2023_consolidated', 'YBC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2023, khoản lỗ lũy kế của Công ty là 11.442.302.555 đồng chiếm 9,7% vốn đầu tư của chủ sở hữu và nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 167.204.506.512 đồng.'),
('XMC_2017_consolidated', 'XMC', 2017, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMC_2017_parent', 'XMC', 2017, 'parent', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XMC_2016_parent', 'XMC', 2016, 'parent', 'AASCN', 'unqualified', 0, NULL),
('XLV_2025_consolidated', 'XLV', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('YBM_2017_consolidated', 'YBM', 2017, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('XMC_2016_consolidated', 'XMC', 2016, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('XLV_2023_consolidated', 'XLV', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('XLV_2021_consolidated', 'XLV', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('XLV_2020_consolidated', 'XLV', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('XMC_2015_parent', 'XMC', 2015, 'parent', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt', 'unqualified', 0, NULL),
('XLV_2019_consolidated', 'XLV', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('XDH_2025_consolidated', 'XDH', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('XLV_2018_consolidated', 'XLV', 2018, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('XDH_2023_consolidated', 'XDH', 2023, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('XDH_2024_consolidated', 'XDH', 2024, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('XDH_2022_consolidated', 'XDH', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('XDH_2021_consolidated', 'XDH', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam (VAE)', 'unqualified', 0, NULL),
('XDH_2020_consolidated', 'XDH', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('XDH_2019_consolidated', 'XDH', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('XLV_2024_consolidated', 'XLV', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('X77_2025_consolidated', 'X77', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'qualified', 1, 'Nợ ngắn hạn vượt tài sản ngắn hạn 195.302.941.793 đồng; lỗ lũy kế vượt vốn chủ sở hữu 192.684.589.237 đồng; các khoản công nợ phải trả đã quá hạn thanh toán.'),
('XDH_2018_consolidated', 'XDH', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X77_2024_consolidated', 'X77', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'qualified', 1, 'Tại ngày 31/12/2024, nợ ngắn hạn vượt tài sản ngắn hạn 195.332.273.164 đồng; lỗ lũy kế vượt vốn chủ sở hữu 191.334.155.627 đồng; các khoản công nợ đã quá hạn thanh toán. Khả năng hoạt động liên tục phụ thuộc vào kế hoạch thu hồi công nợ, hỗ trợ tài chính từ cổ đông và chủ nợ.'),
('X77_2023_consolidated', 'X77', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'qualified', 1, 'Tại ngày 31/12/2023, nợ ngắn hạn vượt tài sản ngắn hạn 196.673.653.540 đồng; lỗ lũy kế vượt vốn chủ sở hữu 191.280.131.584 đồng; các khoản công nợ phải trả đã quá hạn thanh toán. Khả năng hoạt động liên tục phụ thuộc vào kế hoạch thu hồi công nợ, hỗ trợ tài chính từ cổ đông và chủ nợ. Kiểm toán viên không thu thập đủ bằng chứng về tính khả thi của các kế hoạch này.'),
('X77_2020_consolidated', 'X77', 2020, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 1, 'Tại thời điểm 31/12/2020, Công ty đã ngừng các hoạt động chính, giảm phần lớn số lượng lao động, kết quả kinh doanh trong năm lỗ 8.37 tỷ đồng, lỗ lũy kế vượt quá vốn chủ sở hữu hơn 14 lần, nợ ngắn hạn lớn hơn tài sản ngắn hạn 147 tỷ đồng, ảnh hưởng lớn đến khả năng thanh toán của Công ty.'),
('X77_2019_consolidated', 'X77', 2019, 'consolidated', 'CPA VIETNAM', 'qualified', 1, 'Công ty đã ngừng các hoạt động chính, giảm phần lớn số lượng lao động, kết quả kinh doanh trong năm lỗ 9,66 tỷ đồng, lỗ lũy kế vượt quá vốn chủ sở hữu gần 14 lần, nợ ngắn hạn lớn hơn tài sản ngắn hạn 149 tỷ đồng ảnh hưởng lớn đến khả năng thanh toán của Công ty.'),
('X77_2021_consolidated', 'X77', 2021, 'consolidated', 'CPA VIETNAM', 'qualified', 1, 'Công ty đã ngừng các hoạt động chính, giảm phần lớn số lượng lao động, kết quả kinh doanh trong năm lỗ 7,8 tỷ đồng, lỗ lũy kế vượt quá vốn chủ sở hữu hơn 14 lần, nợ ngắn hạn vượt quá tài sản ngắn hạn 146,4 tỷ đồng, ảnh hưởng lớn đến khả năng thanh toán của Công ty.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('X77_2018_consolidated', 'X77', 2018, 'consolidated', 'CPA VIETNAM', 'qualified', 1, 'Tại thời điểm 31/12/2018, công ty đã ngừng các hoạt động chính, giảm phần lớn số lượng lao động, kết quả kinh doanh trong năm lỗ 9,63 tỷ đồng, lỗ lũy kế vượt quá vốn chủ sở hữu gần 13 lần, nợ ngắn hạn lớn hơn tài sản ngắn hạn 149 tỷ đồng, ảnh hưởng lớn đến khả năng thanh toán của Công ty.'),
('X77_2015_consolidated', 'X77', 2015, 'consolidated', 'Công ty TNHH Kiểm toán Hùng Vương', 'qualified', 1, 'Số lỗ lũy kế tính đến ngày 31/12/2015 là 24.547.264.737 đ, vốn chủ sở hữu của Công ty tại ngày 31/12/2015 là -11.633.461.530 đ, tuy nhiên, tính liên tục hoạt động phụ thuộc vào khả năng duy trì, thanh toán các khoản nợ, sự trợ giúp tài chính từ phía chủ đầu tư và khả năng tìm kiếm, mở rộng thị trường tiêu thụ sản phẩm trong tương lai gần.'),
('XMC_2015_consolidated', 'XMC', 2015, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('YBC_2025_consolidated', 'YBC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt – Chi nhánh tại Hà Nội', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2025, nợ ngắn hạn vượt quá tổng tài sản ngắn hạn là 105.573.612.032 đồng, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục. Tuy nhiên, Công ty vẫn đang có lãi, tiếp tục được các Ngân hàng TMCP Đầu tư và Phát triển Việt Nam - CN Yên Bái và Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam – CN huyện Yên Bình Bắc Yên Bái cho vay. Ban Giám đốc cho rằng các vấn đề trên sẽ không ảnh hưởng đến tính hoạt động liên tục của Công ty.'),
('X26_2023_consolidated', 'X26', 2023, 'consolidated', 'An Việt', 'unqualified', 0, NULL),
('X26_2024_consolidated', 'X26', 2024, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('X26_2021_consolidated', 'X26', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán và Định giá ASCO', 'qualified', 0, NULL),
('X26_2018_consolidated', 'X26', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'qualified', 0, NULL),
('X26_2020_consolidated', 'X26', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'qualified', 0, NULL),
('X26_2019_consolidated', 'X26', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'qualified', 1, 'Công ty chưa xác định được giá trị từng tài sản cố định mới tăng do chưa có báo cáo quyết toán vốn đầu tư được phê duyệt nên Công ty chưa ghi tăng nguyên giá tài sản cố định hình thành từ dự án ''Đi đời tái định cư Nhà máy và Trụ sở Công ty Cổ phần 26''.'),
('X20_2025_consolidated', 'X20', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X26_2017_consolidated', 'X26', 2017, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('X20_2024_consolidated', 'X20', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X20_2023_parent', 'X20', 2023, 'parent', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X20_2023_consolidated', 'X20', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X20_2021_consolidated', 'X20', 2021, 'consolidated', 'ASCO', 'unqualified', 0, NULL),
('X20_2022_consolidated', 'X20', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X20_2021_parent', 'X20', 2021, 'parent', 'ASCO', 'unqualified', 0, NULL),
('X20_2019_consolidated', 'X20', 2019, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('X20_2020_consolidated', 'X20', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('X20_2020_parent', 'X20', 2020, 'parent', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('X20_2017_consolidated', 'X20', 2017, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế Moore Stephens', 'unqualified', 0, NULL),
('X20_2017_parent', 'X20', 2017, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('X20_2019_parent', 'X20', 2019, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('X20_2018_consolidated', 'X20', 2018, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('X20_2018_parent', 'X20', 2018, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('WTC_2025_consolidated', 'WTC', 2025, 'consolidated', 'BDO Vietnam', 'unqualified', 0, NULL),
('WTC_2023_consolidated', 'WTC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán BDO', 'unqualified', 0, NULL),
('WTC_2022_consolidated', 'WTC', 2022, 'consolidated', 'BDO Vietnam', 'unqualified', 0, NULL),
('WTC_2020_consolidated', 'WTC', 2020, 'consolidated', 'Công ty TNHH Kiểm toán BDO', 'unqualified', 0, NULL),
('WTC_2021_consolidated', 'WTC', 2021, 'consolidated', 'Công ty TNHH Kiểm toán BDO (BDO Audit Services Co., Ltd)', 'unqualified', 0, NULL),
('WTC_2018_consolidated', 'WTC', 2018, 'consolidated', 'Công ty TNHH Kiểm toán BDO', 'unqualified', 1, 'Nợ ngắn hạn của đơn vị vượt quá tài sản ngắn hạn tại thời điểm 31/12/2018 là 25.590.363.559 đồng.'),
('WTC_2019_consolidated', 'WTC', 2019, 'consolidated', 'BDO Audit Services Co., Ltd.', 'unqualified', 0, NULL),
('WSS_2024_consolidated', 'WSS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('WTC_2015_consolidated', 'WTC', 2015, 'consolidated', 'Unknown', 'qualified', 1, 'Khoản lỗ lũy kế của đơn vị tại thời điểm 31/12/2015 là 139.299.924.290 đồng vượt quá nguồn vốn kinh doanh của công ty 39.299.924.290 đồng và cũng tại ngày này, khoản nợ ngắn hạn của đơn vị vượt quá tổng tài sản ngắn hạn là 85.133.719.471 đồng.'),
('WSS_2025_consolidated', 'WSS', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WSS_2023_consolidated', 'WSS', 2023, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WSS_2022_consolidated', 'WSS', 2022, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('WSS_2018_consolidated', 'WSS', 2018, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('WSS_2020_consolidated', 'WSS', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('X26_2025_consolidated', 'X26', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('X20_2022_parent', 'X20', 2022, 'parent', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'unqualified', 0, NULL),
('WSS_2017_consolidated', 'WSS', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WSS_2016_consolidated', 'WSS', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WSS_2015_consolidated', 'WSS', 2015, 'consolidated', 'AASC', 'qualified', 0, NULL),
('WSB_2025_consolidated', 'WSB', 2025, 'consolidated', 'KPMG Limited Vietnam', 'unqualified', 0, NULL),
('WSB_2023_consolidated', 'WSB', 2023, 'consolidated', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('WSB_2023_parent', 'WSB', 2023, 'parent', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('WSB_2025_parent', 'WSB', 2025, 'parent', 'KPMG', 'unqualified', 0, NULL),
('WSB_2024_parent', 'WSB', 2024, 'parent', 'KPMG Limited Vietnam', 'unqualified', 0, NULL),
('WSB_2024_consolidated', 'WSB', 2024, 'consolidated', 'KPMG Limited Branch, Vietnam', 'unqualified', 0, NULL),
('WSB_2022_consolidated', 'WSB', 2022, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('WSB_2022_parent', 'WSB', 2022, 'parent', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('WSB_2021_consolidated', 'WSB', 2021, 'consolidated', 'KPMG Limited Branch in Ho Chi Minh City', 'unqualified', 0, NULL),
('WSB_2021_parent', 'WSB', 2021, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('WSS_2019_consolidated', 'WSS', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WSB_2020_consolidated', 'WSB', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('WSB_2018_consolidated', 'WSB', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('WSB_2018_parent', 'WSB', 2018, 'parent', 'KPMG', 'unqualified', 0, NULL),
('WSB_2017_consolidated', 'WSB', 2017, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('WSB_2016_parent', 'WSB', 2016, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('WSB_2017_parent', 'WSB', 2017, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('WSB_2015_consolidated', 'WSB', 2015, 'consolidated', 'PricewaterhouseCoopers Việt Nam', 'qualified', 0, NULL),
('WSB_2016_consolidated', 'WSB', 2016, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('WCS_2025_consolidated', 'WCS', 2025, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2024_consolidated', 'WCS', 2024, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2023_consolidated', 'WCS', 2023, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2020_consolidated', 'WCS', 2020, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2021_consolidated', 'WCS', 2021, 'consolidated', 'AFC Vietnam Auditing Co., Ltd.', 'unqualified', 0, NULL),
('WSS_2021_consolidated', 'WSS', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WCS_2019_consolidated', 'WCS', 2019, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2017_consolidated', 'WCS', 2017, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('VXT_2025_consolidated', 'VXT', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WCS_2016_consolidated', 'WCS', 2016, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('WCS_2018_consolidated', 'WCS', 2018, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'unqualified', 0, NULL),
('VXT_2025_parent', 'VXT', 2025, 'parent', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VXT_2024_parent', 'VXT', 2024, 'parent', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('VXT_2024_consolidated', 'VXT', 2024, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VXT_2023_consolidated', 'VXT', 2023, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VXT_2023_parent', 'VXT', 2023, 'parent', 'AASC', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
