PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTK_2020_consolidated', 'VTK', 2020, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VTK_2019_consolidated', 'VTK', 2019, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTK_2021_consolidated', 'VTK', 2021, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTK_2018_consolidated', 'VTK', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTK_2016_consolidated', 'VTK', 2016, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTK_2017_consolidated', 'VTK', 2017, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTJ_2025_consolidated', 'VTJ', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTJ_2025_parent', 'VTJ', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTK_2015_consolidated', 'VTK', 2015, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTJ_2024_consolidated', 'VTJ', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2023_consolidated', 'VTJ', 2023, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2024_parent', 'VTJ', 2024, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2022_consolidated', 'VTJ', 2022, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2023_parent', 'VTJ', 2023, 'parent', 'AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2021_consolidated', 'VTJ', 2021, 'consolidated', 'AFC Việt Nam', 'unqualified', 0, NULL),
('VTJ_2020_parent', 'VTJ', 2020, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTJ_2020_consolidated', 'VTJ', 2020, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam – Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTI_2025_consolidated', 'VTI', 2025, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 1, 'Công ty có lỗ lũy kế khoảng 261,710 tỷ đồng, vốn chủ sở hữu âm 216,983 tỷ đồng, nợ ngắn hạn vượt tài sản ngắn hạn 218,019 tỷ đồng. Việc cải thiện tình hình tài chính phụ thuộc vào việc tái cấu trúc tài chính và sự hỗ trợ từ các bên liên quan. Công ty đã được các cá nhân tạm ứng 196,896 tỷ đồng để có nguồn tiền thanh toán và đang tiếp tục thảo luận về chuyển quyền đòi nợ.'),
('VTI_2023_consolidated', 'VTI', 2023, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 1, 'Công ty có lỗ lũy kế khoảng 271.430 tỷ đồng, vốn chủ sở hữu âm 226.703 tỷ đồng, nợ ngắn hạn vượt tài sản ngắn hạn khoảng 229.933 tỷ đồng. Việc cải thiện phụ thuộc vào tái cấu trúc tài chính và sự hỗ trợ từ các bên liên quan.'),
('VTI_2024_consolidated', 'VTI', 2024, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 1, 'Tại ngày 31/12/2024, Công ty có lỗ lũy kế khoảng 268,041 tỷ đồng; vốn chủ sở hữu âm 223,314 tỷ đồng; số dư nợ ngắn hạn vượt quá tài sản ngắn hạn khoảng 226,444 tỷ đồng. Việc cải thiện tình hình tài chính, khả năng thanh toán ngắn hạn phụ thuộc vào việc tái cấu trúc tài chính và sắp xếp nguồn tài chính, hỗ trợ từ các bên liên quan của Công ty. Công ty đã ký biên bản thỏa thuận với một số cá nhân bán nợ phải thu, các cá nhân đã tạm ứng trước 196.9 tỷ đồng, tuy nhiên chưa ký kết hợp đồng mua bán nợ chính thức.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTI_2022_consolidated', 'VTI', 2022, 'consolidated', 'An Việt CPA', 'qualified', 1, 'Tại ngày 31/12/2022, Công ty có lỗ lũy kế khoảng 315,894 tỷ đồng làm cho vốn chủ sở hữu âm 271,167 tỷ đồng, số dư nợ ngắn hạn vượt quá tài sản ngắn hạn khoảng 261,656 tỷ đồng. Công ty gặp khó khăn về tài chính và thanh toán, phụ thuộc vào sự hỗ trợ từ Công ty mẹ - Tập đoàn Dệt may Việt Nam.'),
('VTI_2021_consolidated', 'VTI', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'qualified', 1, 'Tại ngày 31 tháng 12 năm 2021, nợ ngắn hạn đã vượt quá tài sản ngắn hạn là 268.724 triệu VND và tổng nợ phải trả đã vượt quá tổng tài sản là 271.288 triệu VND. Công ty có một số khoản vay đã quá hạn trị giá 182.131 triệu VND. Giá trị của giả định hoạt động liên tục phụ thuộc vào việc công ty mẹ, Tập đoàn Dệt may Việt Nam, tiếp tục cung cấp hỗ trợ tài chính.'),
('VTI_2020_consolidated', 'VTI', 2020, 'consolidated', 'KPMG Việt Nam', 'qualified', 1, 'Tại ngày 31 tháng 12 năm 2020, nợ ngắn hạn đã vượt quá tài sản ngắn hạn là 263.908 triệu VND và tổng nợ phải trả đã vượt quá tổng tài sản là 262.727 triệu VND. Công ty có các khoản vay đáng kể cần tái trợ trong vòng 12 tháng kế tiếp, với số khoản vay đã quá hạn là 186.091 triệu VND, cho thấy sự tồn tại của các yếu tố không chắc chắn trọng yếu có thể gây nghi ngờ về khả năng tiếp tục hoạt động.'),
('VTI_2019_consolidated', 'VTI', 2019, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'qualified', 1, 'Công ty nợ ngắn hạn vượt tài sản ngắn hạn 264.104 triệu VND, tổng nợ phải trả vượt tổng tài sản 262.746 triệu VND. Có các khoản vay đáng kể cần tái tài trợ và khoản vay đã quá hạn 189.123 triệu VND. Khả năng tiếp tục hoạt động phụ thuộc vào sự hỗ trợ tài chính từ công ty mẹ Tập đoàn Dệt May Việt Nam.'),
('VTI_2018_consolidated', 'VTI', 2018, 'consolidated', 'KPMG Việt Nam', 'unqualified', 1, 'Nợ ngắn hạn vượt quá tài sản ngắn hạn 264.139 triệu VND (1/1/2018: 133.374 triệu VND), tổng nợ phải trả vượt quá tổng tài sản 262.746 triệu VND (1/1/2018: 246.137 triệu VND). Công ty có các khoản vay đáng kể cần tái tài trợ trong 12 tháng tới. Công ty dựa hoàn toàn vào hỗ trợ tài chính từ công ty mẹ Tập đoàn Dệt May Việt Nam. Vốn chủ sở hữu âm với lỗ lũy kế 307.473 triệu VND.'),
('VTI_2016_consolidated', 'VTI', 2016, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 1, 'Báo cáo tài chính được lập trên cơ sở hoạt động liên tục mặc dù nợ ngắn hạn vượt quá tài sản ngắn hạn 44.625 triệu VND và tổng nợ phải trả vượt quá tổng tài sản 196.935 triệu VND. Công ty có các khoản vay đáng kể cần tái tài trợ trong 12 tháng tới, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể gây nghi ngờ về khả năng tiếp tục hoạt động.'),
('VTH_2025_consolidated', 'VTH', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTH_2024_consolidated', 'VTH', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTH_2023_consolidated', 'VTH', 2023, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTH_2021_consolidated', 'VTH', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTH_2022_consolidated', 'VTH', 2022, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTH_2020_consolidated', 'VTH', 2020, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VTH_2019_consolidated', 'VTH', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTH_2018_consolidated', 'VTH', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTH_2017_consolidated', 'VTH', 2017, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTH_2016_consolidated', 'VTH', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTG_2025_consolidated', 'VTG', 2025, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'disclaimer', 0, NULL),
('VTH_2015_consolidated', 'VTH', 2015, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTG_2024_consolidated', 'VTG', 2024, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam', 'disclaimer', 0, NULL),
('VTG_2023_consolidated', 'VTG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'disclaimer', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTG_2022_consolidated', 'VTG', 2022, 'consolidated', 'AFC Vietnam Auditing Co., Ltd.', 'disclaimer', 0, NULL),
('VTG_2020_consolidated', 'VTG', 2020, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'disclaimer', 0, NULL),
('VTG_2019_consolidated', 'VTG', 2019, 'consolidated', 'CFC Vietnam Auditing Co., Ltd.', 'disclaimer', 1, 'Công ty mẹ và công ty con chưa ghi nhận các khoản tiền thuê đất, tiền thuê cơ sở hạ tầng với số tiền là 175,865,108,112 VND. Ngoài ra, các khoản đầu tư vào công ty liên kết không được hợp nhất theo phương pháp vốn chủ sở hữu do không có báo cáo tài chính.'),
('VTG_2021_consolidated', 'VTG', 2021, 'consolidated', 'AFC Vietnam Auditing Co., Ltd.', 'disclaimer', 1, 'Có các vấn đề ảnh hưởng đến hoạt động liên tục bao gồm: (1) Chưa ghi nhận khoản tiền thuê đất và cơ sở hạ tầng lớn với tổng số tiền 225.221.048.206 VND theo kết luận thanh tra; (2) UBND tỉnh Bà Rịa - Vũng Tàu ban hành quyết định thu hồi đất tại Khu du lịch Biển Đông và Khu du lịch Nghinh Phong mà Công ty mẹ và công ty con đang sử dụng không có hợp đồng; (3) Ảnh hưởng tiêu cực từ đại dịch COVID-19 đến hoạt động kinh doanh dịch vụ.'),
('VTG_2018_consolidated', 'VTG', 2018, 'consolidated', 'Công ty TNHH Kiểm toán VACO - Chi nhánh TP. Hồ Chí Minh', 'disclaimer', 0, NULL),
('VTG_2016_consolidated', 'VTG', 2016, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam (AFC Vietnam Auditing Co., Ltd.)', 'qualified', 0, NULL),
('VTG_2015_consolidated', 'VTG', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (A&C Auditing and Consulting Co., Ltd.)', 'unqualified', 0, NULL),
('VTG_2017_consolidated', 'VTG', 2017, 'consolidated', 'AFC Việt Nam', 'qualified', 0, NULL),
('VTE_2024_consolidated', 'VTE', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTE_2025_consolidated', 'VTE', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTE_2022_consolidated', 'VTE', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTO_2016_consolidated', 'VTO', 2016, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTE_2020_consolidated', 'VTE', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTE_2021_consolidated', 'VTE', 2021, 'consolidated', 'Công ty TNHH Hằng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTE_2018_consolidated', 'VTE', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTE_2017_consolidated', 'VTE', 2017, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTE_2016_consolidated', 'VTE', 2016, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTE_2015_consolidated', 'VTE', 2015, 'consolidated', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTD_2025_consolidated', 'VTD', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTD_2024_parent', 'VTD', 2024, 'parent', 'A&C Auditing and Consulting Co., Ltd. (Baker Tilly A&C)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTD_2025_parent', 'VTD', 2025, 'parent', 'Baker Tilly A&C', 'unqualified', 0, NULL),
('VTD_2023_parent', 'VTD', 2023, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTD_2023_consolidated', 'VTD', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTD_2022_parent', 'VTD', 2022, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTD_2022_consolidated', 'VTD', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTD_2021_parent', 'VTD', 2021, 'parent', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'unqualified', 0, NULL),
('VTD_2021_consolidated', 'VTD', 2021, 'consolidated', 'Đất Việt', 'unqualified', 0, NULL),
('VTC_2025_parent', 'VTC', 2025, 'parent', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VTC_2024_parent', 'VTC', 2024, 'parent', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VTC_2024_consolidated', 'VTC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VTC_2025_consolidated', 'VTC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VTC_2023_consolidated', 'VTC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTM_2015_consolidated', 'VTM', 2015, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VTC_2022_consolidated', 'VTC', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTC_2021_consolidated', 'VTC', 2021, 'consolidated', 'VIETVALUES', 'unqualified', 0, NULL),
('VTC_2020_consolidated', 'VTC', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTC_2019_consolidated', 'VTC', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt', 'unqualified', 0, NULL),
('VTC_2018_consolidated', 'VTC', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTC_2017_consolidated', 'VTC', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'unqualified', 0, NULL),
('VTC_2016_parent', 'VTC', 2016, 'parent', 'Công ty TNHH Kiểm toán DFK Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTC_2016_consolidated', 'VTC', 2016, 'consolidated', 'Công ty TNHH Kiểm toán DFK Việt Nam', 'unqualified', 0, NULL),
('VTC_2015_consolidated', 'VTC', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam (VAE)', 'unqualified', 0, NULL),
('VTB_2025_consolidated', 'VTB', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VTB_2025_parent', 'VTB', 2025, 'parent', 'CPA VIETNAM', 'unqualified', 0, NULL),
('VTB_2024_parent', 'VTB', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2024_consolidated', 'VTB', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2023_consolidated', 'VTB', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2022_consolidated', 'VTB', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2023_parent', 'VTB', 2023, 'parent', 'UHY', 'unqualified', 0, NULL),
('VTB_2022_parent', 'VTB', 2022, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2021_consolidated', 'VTB', 2021, 'consolidated', 'UHY Vietnam', 'unqualified', 0, NULL),
('VTB_2020_consolidated', 'VTB', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2020_parent', 'VTB', 2020, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2021_parent', 'VTB', 2021, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2019_consolidated', 'VTB', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2018_consolidated', 'VTB', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2019_parent', 'VTB', 2019, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VTB_2017_consolidated', 'VTB', 2017, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VTB_2018_parent', 'VTB', 2018, 'parent', 'UHY Auditing and Consulting Co Ltd', 'unqualified', 0, NULL),
('VTB_2017_parent', 'VTB', 2017, 'parent', 'AASCS - Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTB_2016_parent', 'VTB', 2016, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VTB_2016_consolidated', 'VTB', 2016, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VTB_2015_parent', 'VTB', 2015, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VTB_2015_consolidated', 'VTB', 2015, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VTA_2025_consolidated', 'VTA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 1, 'Công ty đã ngừng hoạt động sản xuất từ tháng 11 năm 2024 cho đến hết năm 2025. Các khoản nợ ngắn hạn đã vượt quá tài sản ngắn hạn 49.137.482.604 VND. Lỗ lũy kế 102.243.618.746 VND làm thâm hụt vốn chủ sở hữu 11.461.418.746 VND. Điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VTA_2024_consolidated', 'VTA', 2024, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 1, 'Tại ngày 31/12/2024, nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn 47.054.994.209 VND. Công ty lỗ 34.987.921.159 VND trong năm và có lỗ lũy kế 85.127.527.792 VND. Công ty đã ngừng sản xuất từ 11/2024 đến 02/2025. Khả năng hoạt động liên tục phụ thuộc vào quyết định của cổ đông lớn và kế hoạch tái cơ cấu.'),
('VTA_2023_consolidated', 'VTA', 2023, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 1, 'Tại ngày 31/12/2023, các khoản nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn số tiền 28.117.348.195 VND. Công ty có kết quả kinh doanh lỗ 28.541.560.957 VND và khoản lỗ lũy kế là 50.712.106.001 VND. Khả năng tiếp tục hoạt động phụ thuộc vào sự hỗ trợ tài chính từ các chủ đầu tư, khả năng thu hồi các khoản phải thu, gia hạn nợ với các nhà cung cấp, bên cho vay và hiệu quả hoạt động kinh doanh trong tương lai.'),
('VTA_2022_consolidated', 'VTA', 2022, 'consolidated', 'CPA Vietnam', 'unqualified', 0, NULL),
('VTA_2021_consolidated', 'VTA', 2021, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN CPA VIETNAM', 'unqualified', 0, NULL),
('VTA_2020_consolidated', 'VTA', 2020, 'consolidated', 'CPA VIETNAM', 'unqualified', 0, NULL),
('VTE_2023_consolidated', 'VTE', 2023, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTA_2016_consolidated', 'VTA', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt - VIETVALUES', 'unqualified', 0, NULL),
('VTA_2017_consolidated', 'VTA', 2017, 'consolidated', 'VIETVALUES', 'unqualified', 0, NULL),
('VST_2025_consolidated', 'VST', 2025, 'consolidated', 'AASC Auditing Firm', 'qualified', 1, 'Tại thời điểm 31/12/2025, nợ ngắn hạn đã vượt quá tài sản ngắn hạn của Công ty là 623,48 tỷ VND, lỗ lũy kế là 1.129,82 tỷ VND, chỉ tiêu vốn chủ sở hữu âm 423,17 tỷ VND. Các khoản nợ vay đã quá hạn thanh toán 190 tỷ VND. Công ty chưa có phương án hiệu quả để khắc phục khả năng thanh khoản cũng như tìm kiếm được nguồn tiền để thanh toán cho các khoản vay đến hạn trong vòng 12 tháng tới trong điều kiện hoạt động bình thường.'),
('VTA_2015_consolidated', 'VTA', 2015, 'consolidated', 'VIETVALUES', 'unqualified', 0, NULL),
('VST_2024_consolidated', 'VST', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'qualified', 1, 'Tại thời điểm 31/12/2024, nợ ngắn hạn vượt quá tài sản ngắn hạn 734,51 tỷ VND, lỗ lũy kế 1.375,76 tỷ VND, vốn chủ sở hữu âm 669,11 tỷ VND. Nợ vay quá hạn thanh toán 218,72 tỷ VND. Công ty chưa có phương án hiệu quả để khắc phục khả năng thanh khoản và thanh toán khoản vay đến hạn trong 12 tháng tới.'),
('VST_2023_parent', 'VST', 2023, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 1, 'Tại thời điểm 31/12/2023, nợ ngắn hạn đã vượt quá tài sản ngắn hạn là 1.008 tỷ đồng, lỗ lũy kế là 1.595 tỷ đồng, chỉ tiêu vốn chủ sở hữu âm 908 tỷ đồng. Các khoản nợ vay đã quá hạn thanh toán lên tới 279 tỷ đồng, chi phí lãi vay phải trả cho các khoản vay quá hạn là 749 tỷ đồng. Công ty đã có phương án tái cơ cấu tài chính nhưng chưa xác định được tính hiệu quả.'),
('VST_2023_consolidated', 'VST', 2023, 'consolidated', 'AASC Auditing Firm', 'qualified', 1, 'Tại thời điểm 31/12/2023, nợ ngắn hạn vượt tài sản ngắn hạn 970 tỷ đồng, lỗ lũy kế 1,592 tỷ đồng, vốn chủ sở hữu âm 905 tỷ đồng. Nợ vay quá hạn thanh toán 279 tỷ đồng, chi phí lãi vay phải trả 749 tỷ đồng. Công ty có phương án tái cơ cấu tài chính nhưng chưa xác định hiệu quả.'),
('VST_2021_parent', 'VST', 2021, 'parent', 'AASC Auditing Firm', 'qualified', 1, 'Tại thời điểm 31/12/2021, nợ ngắn hạn đã vượt quá tài sản ngắn hạn của Công ty là 2.148 tỷ đồng, lỗ lũy kế là 2.370 tỷ đồng, chỉ tiêu vốn chủ âm 1.726 tỷ đồng; lưu chuyển tiền thuần trong năm trên báo cáo lưu chuyển tiền tệ âm 548 triệu đồng. Các khoản nợ vay đã quá hạn thanh toán lên tới 824 tỷ đồng, chi phí lãi vay phải trả cho các khoản vay quá hạn này là 1.105 tỷ đồng. Công ty chưa có phương án hiệu quả để khắc phục khả năng thanh khoản cũng như tìm kiếm được nguồn tiền để thanh toán cho các khoản vay đến hạn trong vòng 12 tháng tới trong điều kiện hoạt động bình thường. Công ty cũng đang đối mặt với các vụ kiện của Ngân hàng về việc phải thanh toán ngay các khoản vay. Những sự kiện này, cùng với các vấn đề được nêu ở Thuyết minh số 1, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VST_2022_consolidated', 'VST', 2022, 'consolidated', 'AASC', 'qualified', 1, 'Tại thời điểm 31/12/2022, nợ ngắn hạn đã vượt quá tài sản ngắn hạn của Công ty là 1.519 tỷ đồng, lỗ lũy kế là 2.159 tỷ đồng, chỉ tiêu vốn chủ âm 1.514 tỷ đồng. Đồng thời các khoản nợ vay đã quá hạn thanh toán lên tới 332 tỷ đồng. Chi phí lãi vay phải trả cho các khoản vay quá hạn này là 1.204 tỷ đồng. Công ty đang triển khai phương án hiệu quả để khắc phục khả năng thanh khoản nhưng gặp khó khăn trong việc tìm kiếm được nguồn tiền để thanh toán cho các khoản vay đến hạn trong vòng 12 tháng tới trong điều kiện hoạt động bình thường.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VST_2021_consolidated', 'VST', 2021, 'consolidated', 'AASC Auditing Firm', 'qualified', 1, 'Công ty chưa có phương án hiệu quả để khắc phục khả năng thanh khoản cũng như tìm kiếm được nguồn tiền để thanh toán cho các khoản vay đến hạn trong vòng 12 tháng tới trong điều kiện hoạt động bình thường.'),
('VST_2020_consolidated', 'VST', 2020, 'consolidated', 'AASC', 'qualified', 1, 'Nợ ngắn hạn vượt tài sản ngắn hạn 2.133 tỷ đồng, lỗ lũy kế 2.361 tỷ đồng, vốn chủ sở hữu âm 1.716 tỷ đồng, lưu chuyển tiền thuần âm 16 tỷ đồng. Các khoản nợ vay đã quá hạn thanh toán là 793 tỷ đồng, công ty đang bị kiện bởi ngân hàng và chưa có phương án hiệu quả để khắc phục khả năng thanh khoản.'),
('VST_2019_consolidated', 'VST', 2019, 'consolidated', 'Hãng Kiểm toán AASC', 'qualified', 1, 'Tại thời điểm 31/12/2019, nợ ngắn hạn đã vượt quá tài sản ngắn hạn của Công ty là 1.893 tỷ đồng, lỗ lũy kế là 2.053 tỷ đồng, chỉ tiêu vốn chủ đã bị âm 1.429 tỷ đồng. Đồng thời tại thuyết minh số 19 - Vay, các khoản nợ vay đã quá hạn thanh toán lên tới 736 tỷ đồng, của Ngân hàng Phát triển Việt Nam và Ngân hàng TMCP Á Châu.'),
('VST_2018_consolidated', 'VST', 2018, 'consolidated', 'VIETVALUES', 'qualified', 1, 'Năm tài chính kết thúc ngày 31 tháng 12 năm 2018, Tập đoàn tiếp tục lỗ với số tiền 255.299.656.797 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2018 là 1.780.778.706.889 VND. Ngoài ra tại ngày 31 tháng 12 năm 2018, nợ ngắn hạn lớn hơn tài sản ngắn hạn với số tiền 1.899.127.933.882 VND. Các khoản nợ vay đã quá hạn thanh toán, Tập đoàn đang đàm phán lại nhưng chưa có thỏa thuận tài chính thay thế.'),
('VST_2015_parent', 'VST', 2015, 'parent', 'Công ty TNHH Kiểm toán và Kế toán Hà Nội - CPA Hà Nội', 'unqualified', 1, 'Báo cáo tài chính của Công ty cổ phần Vận tải và Thuê tàu biển Việt Nam cho năm tài chính 2015 được lập dựa trên giả định hoạt động liên tục. Đến cuối năm tài chính 2015, Công ty có nhiều biện pháp được triển khai để tái cơ cấu doanh nghiệp. Trong năm tài chính tiếp theo, doanh nghiệp khẳng định tiếp tục hoạt động liên tục nhờ các biện pháp triển khai đang thực hiện có hiệu quả.'),
('VST_2015_consolidated', 'VST', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Kế toán Hà Nội - CPA Hà Nội', 'unqualified', 1, 'Báo cáo tài chính được lập dựa trên giả định hoạt động liên tục. Công ty có nhiều biện pháp được triển khai để tái cơ cấu doanh nghiệp và khẳng định tiếp tục hoạt động liên tục.'),
('VSN_2025_consolidated', 'VSN', 2025, 'consolidated', 'UHY', 'unqualified', 0, NULL),
('VSN_2022_consolidated', 'VSN', 2022, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2023_consolidated', 'VSN', 2023, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2024_consolidated', 'VSN', 2024, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2021_consolidated', 'VSN', 2021, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2019_consolidated', 'VSN', 2019, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2020_consolidated', 'VSN', 2020, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSN_2018_consolidated', 'VSN', 2018, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VSN_2017_consolidated', 'VSN', 2017, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VSN_2016_consolidated', 'VSN', 2016, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSN_2015_consolidated', 'VSN', 2015, 'consolidated', 'Công ty TNHH Kiểm toán DTL', 'unqualified', 0, NULL),
('VSM_2024_consolidated', 'VSM', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Kế toán AAC', 'unqualified', 0, NULL),
('VSM_2025_consolidated', 'VSM', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Kế toán AAC', 'unqualified', 0, NULL),
('VSM_2023_parent', 'VSM', 2023, 'parent', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSM_2023_consolidated', 'VSM', 2023, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VST_2018_parent', 'VST', 2018, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt (VIETVALUES)', 'qualified', 1, 'Năm tài chính kết thúc ngày 31 tháng 12 năm 2018, Công ty tiếp tục lỗ với số tiền (255.140.928.381) VND và khoản lỗ luỹ kế đến ngày 31 tháng 12 năm 2018 với số tiền (1.780.285.817.722) VND. Nợ ngắn hạn lớn hơn tài sản ngắn hạn với số tiền 1.903.095.614.539 VND. Các khoản nợ vay đã quá hạn thanh toán và Công ty chưa có thỏa thuận tài chính thay thế, đặt ra nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VSM_2022_consolidated', 'VSM', 2022, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSM_2021_parent', 'VSM', 2021, 'parent', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSM_2021_consolidated', 'VSM', 2021, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSM_2019_consolidated', 'VSM', 2019, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSM_2020_parent', 'VSM', 2020, 'parent', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSM_2020_consolidated', 'VSM', 2020, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSH_2025_consolidated', 'VSH', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSM_2019_parent', 'VSM', 2019, 'parent', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSH_2025_parent', 'VSH', 2025, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VSH_2024_consolidated', 'VSH', 2024, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2023_consolidated', 'VSH', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2024_parent', 'VSH', 2024, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2022_consolidated', 'VSH', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2023_parent', 'VSH', 2023, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2022_parent', 'VSH', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2021_consolidated', 'VSH', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2021_parent', 'VSH', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2020_parent', 'VSH', 2020, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSH_2020_consolidated', 'VSH', 2020, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2019_parent', 'VSH', 2019, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2018_consolidated', 'VSH', 2018, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'qualified', 0, NULL),
('VSH_2019_consolidated', 'VSH', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2018_parent', 'VSH', 2018, 'parent', 'Ernst & Young Việt Nam', 'qualified', 0, NULL),
('VSH_2017_consolidated', 'VSH', 2017, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VSH_2016_consolidated', 'VSH', 2016, 'consolidated', 'PricewaterhouseCoopers Việt Nam', 'unqualified', 0, NULL),
('VSH_2016_parent', 'VSH', 2016, 'parent', 'PricewaterhouseCoopers Việt Nam', 'unqualified', 0, NULL),
('VSH_2017_parent', 'VSH', 2017, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VSH_2015_consolidated', 'VSH', 2015, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VSH_2015_parent', 'VSH', 2015, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VSI_2025_consolidated', 'VSI', 2025, 'consolidated', 'AASCS', 'unqualified', 0, NULL),
('VSI_2024_parent', 'VSI', 2024, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2025_parent', 'VSI', 2025, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2024_consolidated', 'VSI', 2024, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2023_consolidated', 'VSI', 2023, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VTA_2019_consolidated', 'VTA', 2019, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VSI_2022_consolidated', 'VSI', 2022, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2023_parent', 'VSI', 2023, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2021_consolidated', 'VSI', 2021, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSI_2021_parent', 'VSI', 2021, 'parent', 'CÔNG TY TNHH DỊCH VỤ TƯ VĂN TÀI CHÍNH KẾ TOÁN VÀ KIỂM TOÁN PHÍA NAM (AASCS)', 'unqualified', 0, NULL),
('VSI_2019_consolidated', 'VSI', 2019, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2019_parent', 'VSI', 2019, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2020_parent', 'VSI', 2020, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2018_parent', 'VSI', 2018, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2018_consolidated', 'VSI', 2018, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2017_consolidated', 'VSI', 2017, 'consolidated', 'CÔNG TY TNHH DỊCH VỤ TƯ VẤN TÀI CHÍNH KẾ TOÁN VÀ KIỂM TOÁN PHÍA NAM (AASCS)', 'unqualified', 0, NULL),
('VSI_2017_parent', 'VSI', 2017, 'parent', 'AASCS', 'unqualified', 0, NULL),
('VSI_2016_consolidated', 'VSI', 2016, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2016_parent', 'VSI', 2016, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2015_consolidated', 'VSI', 2015, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSI_2015_parent', 'VSI', 2015, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSG_2024_consolidated', 'VSG', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'disclaimer', 1, 'Năm tài chính kết thúc ngày 31 tháng 12 năm 2024 Công ty tiếp tục bị lỗ 69,793,438,920 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2024 là 934,719,728,207 VND, vượt vốn góp của chủ sở hữu 767,520,103,053 VND. Nợ ngắn hạn lớn hơn tài sản ngắn hạn 797,076,675,515 VND. Công ty đã hoàn trả tất cả tàu đi thuê từ Ngân hàng TMCP Hàng Hải Việt Nam từ ngày 06 tháng 02 năm 2024, do vậy sẽ không còn phát sinh doanh thu cho thuê tàu. Các điều kiện này cho thấy sự tồn tại của các yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VSG_2025_consolidated', 'VSG', 2025, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'disclaimer', 1, 'Số lỗ luỹ kế tại thời điểm 31/12/2025 là 984.288.733.480 VND đã vượt số vốn điều lệ và vốn chủ sở hữu. Nợ phải trả lớn hơn Tổng tài sản là 817.089.108.326 VND, như vậy Công ty đã không duy trì được khả năng thanh toán. Ngoài ra Nợ ngắn hạn lớn hơn Tài sản ngắn hạn 844.947.103.580 VND, như vậy khả năng thanh toán nợ ngắn hạn của Công ty cũng không đảm bảo. Thêm vào đó, kể từ ngày 06/02/2024, Công ty cũng đã hoàn trả tất cả tàu đi thuê từ Ngân hàng TMCP Hàng Hải Việt Nam - Chi nhánh TP.HCM, do đó sẽ không còn phát sinh doanh thu cho thuê tàu từ thời điểm này.'),
('VSG_2022_consolidated', 'VSG', 2022, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ TƯ VÁN A&C', 'unqualified', 0, NULL),
('VSG_2023_consolidated', 'VSG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VSG_2021_consolidated', 'VSG', 2021, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 1, 'Công ty tiếp tục bị lỗ 103.871.857.393 VND và khoản lỗ luỹ kế đến ngày 31 tháng 12 năm 2021 là 701.655.399.367 VND, vượt vốn góp của chủ sở hữu 534.455.774.213 VND. Ngoài ra tại ngày 31 tháng 12 năm 2021 nợ ngắn hạn lớn hơn tài sản ngắn hạn một khoản 570.411.254.471 VND. Những điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VSG_2020_consolidated', 'VSG', 2020, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 1, 'Công ty tiếp tục bị lỗ 39.593.803.277 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2020 là 597.783.541.974 VND, vượt vốn chủ sở hữu 430.583.916.820 VND. Ngoài ra, nợ ngắn hạn lớn hơn tài sản ngắn hạn một khoản là 554.937.300.931 VND. Công ty đang đàm phán với Ngân hàng TMCP Hàng hải Việt Nam để có kế hoạch trả nợ phù hợp với tình hình hoạt động kinh doanh.'),
('VSG_2019_consolidated', 'VSG', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 1, 'Công ty tiếp tục bị lỗ lũy kế đến ngày 31 tháng 12 năm 2019 là 558.189.738.697 VND, vượt vốn chủ sở hữu 390.990.113.543 VND. Nợ ngắn hạn lớn hơn tài sản ngắn hạn 577.259.103.620 VND. Các yếu tố này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VSG_2018_consolidated', 'VSG', 2018, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 1, 'Trong năm tài chính kết thúc ngày 31 tháng 12 năm 2018 Công ty tiếp tục bị lỗ 54.216.871.590 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2018 là 523.776.736.851 VND. Ngoài ra tại ngày 31 tháng 12 năm 2018 nợ ngắn hạn lớn hơn tài sản ngắn hạn 527.934.099.738 VND.');
PRAGMA foreign_keys = ON;
