PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPH_2022_consolidated', 'VPH', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP. Hồ Chí Minh', 'unqualified', 0, NULL),
('VPH_2020_consolidated', 'VPH', 2020, 'consolidated', 'Công ty TNHH Kiểm Toán & Tư Vấn UHY - Chi nhánh TP. Hồ Chí Minh', 'unqualified', 0, NULL),
('VPH_2021_parent', 'VPH', 2021, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP.HCM', 'unqualified', 0, NULL),
('VPH_2020_parent', 'VPH', 2020, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP.HCM', 'unqualified', 0, NULL),
('VPH_2019_parent', 'VPH', 2019, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VPH_2021_consolidated', 'VPH', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP.HCM', 'unqualified', 1, 'Ủy ban Nhân dân TP.HCM đã quyết định đình chỉ hoạt động kinh doanh bất động sản trong 12 tháng từ ngày 02/06/2021 theo Quyết định số 2005/QĐ-XPVPHC liên quan đến Dự án Khu dân cư Nhơn Đức. Tại Văn bản số 876/SXD-TT ngày 21/01/2022, Sở Xây dựng TP.HCM chấp thuận không áp dụng hình thức phạt bổ sung trong 6 tháng còn lại (từ 02/12/2021 đến 02/06/2022). Báo cáo tài chính được lập trên cơ sở đáp ứng giả định hoạt động liên tục.'),
('VPH_2019_consolidated', 'VPH', 2019, 'consolidated', 'PKF Vietnam', 'unqualified', 0, NULL),
('VPH_2018_consolidated', 'VPH', 2018, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VPH_2018_parent', 'VPH', 2018, 'parent', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VPH_2017_consolidated', 'VPH', 2017, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VPH_2017_parent', 'VPH', 2017, 'parent', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VPG_2025_consolidated', 'VPG', 2025, 'consolidated', 'UHY Auditing and Consulting Company Limited', 'qualified', 0, NULL),
('VPG_2025_parent', 'VPG', 2025, 'parent', 'UHY Auditing and Consulting Co., Ltd.', 'qualified', 0, NULL),
('VPG_2024_parent', 'VPG', 2024, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPG_2024_consolidated', 'VPG', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPG_2023_parent', 'VPG', 2023, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPG_2023_consolidated', 'VPG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPG_2022_consolidated', 'VPG', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPD_2024_consolidated', 'VPD', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VPG_2022_parent', 'VPG', 2022, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPD_2023_consolidated', 'VPD', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VPD_2025_consolidated', 'VPD', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPD_2021_consolidated', 'VPD', 2021, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('VPD_2020_consolidated', 'VPD', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPD_2015_consolidated', 'VPD', 2015, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPD_2017_consolidated', 'VPD', 2017, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VPB_2025_consolidated', 'VPB', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPD_2016_consolidated', 'VPD', 2016, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VPB_2025_parent', 'VPB', 2025, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2024_parent', 'VPB', 2024, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2024_consolidated', 'VPB', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2022_consolidated', 'VPB', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2022_parent', 'VPB', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2021_consolidated', 'VPB', 2021, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VPB_2021_parent', 'VPB', 2021, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VPB_2020_consolidated', 'VPB', 2020, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VPB_2019_consolidated', 'VPB', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2020_parent', 'VPB', 2020, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VPB_2019_parent', 'VPB', 2019, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2018_consolidated', 'VPB', 2018, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPB_2017_consolidated', 'VPB', 2017, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2018_parent', 'VPB', 2018, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPB_2017_parent', 'VPB', 2017, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPA_2025_consolidated', 'VPA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 1, 'Khoản lỗ lũy kế đến ngày 31/12/2025 là hơn 245 tỷ đồng (vượt quá vốn góp của chủ sở hữu hơn 94 tỷ đồng) và tại ngày 31/12/2025, số dư nợ ngắn hạn lớn hơn tài sản ngắn hạn 9 tỷ đồng. Công ty đã đạt được thỏa thuận với ngân hàng cho vay về việc giãn nợ gốc và lãi vay phải trả trong ngắn hạn nhưng vẫn gặp nhiều khó khăn về tài chính, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VPA_2024_consolidated', 'VPA', 2024, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 1, 'Khoản lỗ lũy kế đến ngày 31/12/2024 là hơn 200 tỷ đồng (vượt quá vốn góp của chủ sở hữu gần 61 tỷ đồng) và tại ngày 31/12/2024, số dư nợ ngắn hạn lớn hơn tài sản ngắn hạn xấp xỉ 22 tỷ đồng.'),
('VPA_2020_consolidated', 'VPA', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VPA_2022_consolidated', 'VPA', 2022, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 1, 'Tính đến ngày 31/12/2022, Công ty có khoản lỗ lũy kế là 147.798.372.185 VND và số dư nợ ngắn hạn đã vượt tài sản ngắn hạn 19.152.331.904 VND, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VPA_2023_consolidated', 'VPA', 2023, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 1, 'Lỗ lũy kế đến ngày 31/12/2023 là 161.587.109.469 VND, vượt quá vốn góp của chủ sở hữu 10.825.339.469 VND. Tuy nhiên, ý kiến kiểm toán viên không bị ảnh hưởng bởi vấn đề này.'),
('VPA_2019_consolidated', 'VPA', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VPA_2021_consolidated', 'VPA', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('VPA_2018_consolidated', 'VPA', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VPA_2016_consolidated', 'VPA', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VPA_2017_consolidated', 'VPA', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn tài chính Quốc tế (IFC)', 'unqualified', 0, NULL),
('VNZ_2025_consolidated', 'VNZ', 2025, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 1, 'Tập đoàn phát sinh lỗ sau thuế 325.984.545.132 VND năm 2025 và tổng nợ ngắn hạn vượt tổng tài sản ngắn hạn 494.246.887.290 VND. Khả năng hoạt động liên tục phụ thuộc vào hoạt động kinh doanh có lợi nhuận trong tương lai và kế hoạch dòng tiền.'),
('VPA_2015_consolidated', 'VPA', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Tài chính Quốc tế (IFC)', 'unqualified', 1, 'Tổng Nợ ngắn hạn tại ngày 31/12/2015 vượt quá tổng Tài sản ngắn hạn 27.189.717.621 đồng. Lỗ lũy kế là 18.761.670.713 đồng. Khoản nợ ngắn hạn lớn hơn tài sản ngắn hạn chủ yếu do khoản nợ phải trả của Công ty TNHH MTV Đóng tàu Hồng Hà tăng do quyết toán vốn đầu tư tàu VP1 và VP2.'),
('VNZ_2025_parent', 'VNZ', 2025, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 1, 'Công ty phát sinh lỗ sau thuế 277,013,858,968 VNĐ năm 2025 và tổng nợ ngắn hạn vượt tài sản ngắn hạn 2,451,093,379,250 VNĐ. Khả năng hoạt động liên tục phụ thuộc vào kế hoạch kinh doanh có lợi nhuận và nguồn tài trợ bổ sung.'),
('VNZ_2023_consolidated', 'VNZ', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 1, 'Tập đoàn phát sinh khoản lỗ thuần sau thuế với giá trị là 2.317.244.894.436 VND cho năm tài chính kết thúc ngày 31 tháng 12 năm 2023. Điều kiện này cho thấy có sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Tập đoàn. Tuy nhiên, Ban Tổng Giám đốc tin tưởng rằng, dựa trên kế hoạch dòng tiền dự phòng, Tập đoàn có thể đảm bảo đủ nguồn tiền để đáp ứng nhu cầu trong 12 tháng tới.'),
('VNZ_2024_consolidated', 'VNZ', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 1, 'Công ty đã phát sinh khoản lỗ sau thuế thu nhập doanh nghiệp 1.808.101.943.534 VND cho năm tài chính kết thúc ngày 31/12/2024. Tổng nợ ngắn hạn vượt hơn tổng tài sản ngắn hạn 2.420.429.943.917 VND tại ngày 31/12/2024, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VNZ_2023_parent', 'VNZ', 2023, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 1, 'Công ty phát sinh khoản lỗ thuần sau thuế với giá trị 341.341.410.151 VND cho năm tài chính kết thúc ngày 31/12/2023. Điều kiện này cho thấy có sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty. Công ty đã lập kế hoạch cho 12 tháng tiếp theo để cải thiện dòng tiền từ hoạt động kinh doanh.'),
('VNY_2025_consolidated', 'VNY', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNZ_2022_consolidated', 'VNZ', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNZ_2022_parent', 'VNZ', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNY_2024_parent', 'VNY', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNY_2025_parent', 'VNY', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNY_2024_consolidated', 'VNY', 2024, 'consolidated', 'UHY', 'unqualified', 0, NULL),
('VNY_2023_consolidated', 'VNY', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNY_2023_parent', 'VNY', 2023, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNY_2022_parent', 'VNY', 2022, 'parent', 'CÔNG TY TNHH KIỂM TOÁN VÀ TƯ VÁN UHY', 'unqualified', 0, NULL),
('VNY_2022_consolidated', 'VNY', 2022, 'consolidated', 'UHY', 'unqualified', 0, NULL),
('VNY_2021_consolidated', 'VNY', 2021, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh Miền Bắc', 'unqualified', 1, 'Tại thời điểm 31/12/2021, số lỗ lũy kế của đơn vị là 192.367.273.123 đồng vượt 49.867.583.123 đồng so với số vốn góp của chủ sở hữu. Nợ ngắn hạn vượt quá tài sản ngắn hạn là 21.828.885.834 đồng, chỉ ra yếu tố không chắc chắn trọng yếu ảnh hưởng đến khả năng hoạt động liên tục.'),
('VNY_2021_parent', 'VNY', 2021, 'parent', 'CPA VIETNAM – Chi nhánh Miền Bắc', 'unqualified', 1, 'Lỗ lũy kế vượt 49.867.583.123 đồng so với vốn góp và nợ phải trả ngắn hạn vượt tài sản ngắn hạn 3.363.896.215 đồng.'),
('VNY_2020_consolidated', 'VNY', 2020, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh Miền Bắc', 'unqualified', 1, 'Tại thời điểm 31/12/2020, số lỗ lũy kế của đơn vị là 200.324.718.467 đồng vượt 113.986.572.988 đồng so với số vốn đầu tư của chủ sở hữu cùng thời điểm. Và cũng tại ngày đó, nợ ngắn hạn của đơn vị đã vượt quá tài sản ngắn hạn của đơn vị là 209.138.098.637 đồng. Các dấu hiệu trên chỉ ra yếu tố không chắc chắn trọng yếu ảnh hưởng đến khả năng hoạt động liên tục của đơn vị.'),
('VNY_2020_parent', 'VNY', 2020, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM – Chi nhánh Miền Bắc', 'unqualified', 1, 'Tại thời điểm 31/12/2020, số lỗ lũy kế của đơn vị là 200.324.718.467 đồng vượt 117.241.479.529 đồng so với số vốn đầu tư của chủ sở hữu cùng thời điểm. Khoản nợ phải trả của đơn vị đã vượt quá tài sản ngắn hạn của đơn vị là 187.001.251.582 đồng. Các dấu hiệu trên chỉ ra yếu tố không chắc chắn trọng yếu ảnh hưởng đến khả năng hoạt động liên tục của đơn vị.'),
('VNY_2019_parent', 'VNY', 2019, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh Miền Bắc', 'qualified', 1, 'Tại thời điểm 31/12/2019, số lỗ lũy kế của đơn vị là 202.078.403.727 đồng vượt 118.995.164.789 đồng so với số vốn đầu tư của chủ sở hữu cùng thời điểm. Và cũng tại ngày đó, khoản nợ phải trả của đơn vị đã vượt quá tài sản ngắn hạn của đơn vị là 199.675.304.969 đồng. Các dấu hiệu trên chỉ ra yếu tố không chắc chắn trọng yếu ảnh hưởng đến khả năng hoạt động liên tục của đơn vị.'),
('VNY_2018_consolidated', 'VNY', 2018, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 1, 'Lỗ lũy kế 182.273.994.532 đồng vượt 95.935.849.053 đồng so với vốn đầu tư của chủ sở hữu; nợ phải trả vượt tài sản ngắn hạn 211.334.345.509 đồng.'),
('VNY_2017_consolidated', 'VNY', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'qualified', 1, 'Khoản lỗ sau thuế chưa phân phối lũy kế đến 31/12/2017 là 166.273.730.338 đồng đã vượt Vốn chủ sở hữu (79.863.035.706 đồng). Công ty đang mất khả năng thanh toán các khoản nợ ngắn hạn, cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về hoạt động liên tục.'),
('VNY_2017_parent', 'VNY', 2017, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'qualified', 1, 'Khoản lỗ sau thuế chưa phân phối lũy kế của Công ty đến ngày 31/12/2017 là 166.273.730.338 đồng đã vượt Vốn chủ sở hữu số tiền 83.117.942.247 đồng, và theo đánh giá của Ban lãnh đạo Công ty tại thuyết minh số 13 Công ty đang mất khả năng thanh toán các khoản nợ ngắn hạn, điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về hoạt động liên tục của Công ty.'),
('VNY_2019_consolidated', 'VNY', 2019, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh Miền Bắc', 'qualified', 1, 'Tại thời điểm 31/12/2019, số lỗ lũy kế của đơn vị là 199.086.965.040 đồng vượt 112.748.819.561 đồng so với số vốn đầu tư của chủ sở hữu cùng thời điểm. Nợ ngắn hạn vượt quá tài sản ngắn hạn là 69.699.571.078 đồng. Kiểm toán viên không đủ cơ sở để xác định 03 khoản vay cá nhân với tổng số tiền 19.991.125.000 đồng và lãi phải trả 2.005.858.000 đồng do không có hợp đồng vay giữa Công ty và các cá nhân.'),
('VNX_2021_consolidated', 'VNX', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VNX_2024_consolidated', 'VNX', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNX_2025_consolidated', 'VNX', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('VNX_2022_consolidated', 'VNX', 2022, 'consolidated', 'Công ty TNHH Hãng kiểm toán và Định giá ASCO', 'unqualified', 0, NULL),
('VNX_2020_consolidated', 'VNX', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VNX_2019_consolidated', 'VNX', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VNX_2018_consolidated', 'VNX', 2018, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ THẨM ĐỊNH GIÁ VIỆT NAM (AVA)', 'unqualified', 0, NULL),
('VNX_2017_consolidated', 'VNX', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VNX_2016_consolidated', 'VNX', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VNX_2015_consolidated', 'VNX', 2015, 'consolidated', 'AVA', 'unqualified', 0, NULL),
('VNT_2024_consolidated', 'VNT', 2024, 'consolidated', 'Công ty TNHH Kiểm toán & Tư Vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2025_consolidated', 'VNT', 2025, 'consolidated', 'RSM Việt Nam', 'unqualified', 0, NULL),
('VPR_2016_consolidated', 'VPR', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VNT_2021_consolidated', 'VNT', 2021, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2022_consolidated', 'VNT', 2022, 'consolidated', 'RSM Vietnam', 'unqualified', 0, NULL),
('VNT_2020_consolidated', 'VNT', 2020, 'consolidated', 'RSM Vietnam', 'unqualified', 0, NULL),
('VNT_2019_consolidated', 'VNT', 2019, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2019_parent', 'VNT', 2019, 'parent', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2018_consolidated', 'VNT', 2018, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2018_parent', 'VNT', 2018, 'parent', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2025_parent', 'VNT', 2025, 'parent', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2017_consolidated', 'VNT', 2017, 'consolidated', 'RSM Vietnam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNT_2016_parent', 'VNT', 2016, 'parent', 'Công ty TNHH Kiểm toán & Tư Vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2015_consolidated', 'VNT', 2015, 'consolidated', 'Công ty TNHH Kiểm toán DTL (RSM Vietnam)', 'unqualified', 0, NULL),
('VNT_2016_consolidated', 'VNT', 2016, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL),
('VNSC_2025_consolidated', 'VNSC', 2025, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VNT_2015_parent', 'VNT', 2015, 'parent', 'RSM Vietnam', 'unqualified', 0, NULL),
('VNSC_2024_consolidated', 'VNSC', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNSC_2023_consolidated', 'VNSC', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNSC_2020_consolidated', 'VNSC', 2020, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'unqualified', 0, NULL),
('VNSC_2018_consolidated', 'VNSC', 2018, 'consolidated', 'UHY', 'unqualified', 0, NULL),
('VNSC_2021_consolidated', 'VNSC', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 1, 'Tại ngày 31/12/2021, vốn chủ sở hữu của Công ty là 10.717.837.637 đồng thấp hơn mức vốn điều lệ tối thiểu cho các nghiệp vụ kinh doanh của Công ty theo quy định hiện hành là 35.000.000.000 đồng do phát sinh lỗ lũy kế. Công ty phải đảm bảo vốn chủ sở hữu phải tối thiểu bằng vốn pháp định.'),
('VNSC_2017_consolidated', 'VNSC', 2017, 'consolidated', 'Grant Thornton (Việt Nam)', 'unqualified', 0, NULL),
('VNSC_2016_consolidated', 'VNSC', 2016, 'consolidated', 'Công ty TNHH Grant Thornton (Việt Nam)', 'unqualified', 0, NULL),
('VNSC_2019_consolidated', 'VNSC', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VNT_2023_consolidated', 'VNT', 2023, 'consolidated', 'RSM Việt Nam', 'unqualified', 0, NULL),
('VNT_2023_parent', 'VNT', 2023, 'parent', 'RSM Vietnam', 'unqualified', 0, NULL),
('VNSC_2015_consolidated', 'VNSC', 2015, 'consolidated', 'Grant Thornton (Việt Nam)', 'unqualified', 0, NULL),
('VNS_2025_consolidated', 'VNS', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2024_consolidated', 'VNS', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2023_consolidated', 'VNS', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2024_parent', 'VNS', 2024, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNS_2025_parent', 'VNS', 2025, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2023_parent', 'VNS', 2023, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2022_parent', 'VNS', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2022_consolidated', 'VNS', 2022, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2019_consolidated', 'VNS', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2021_consolidated', 'VNS', 2021, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2019_parent', 'VNS', 2019, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VNS_2020_consolidated', 'VNS', 2020, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2021_parent', 'VNS', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2020_parent', 'VNS', 2020, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2017_consolidated', 'VNS', 2017, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2018_parent', 'VNS', 2018, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2018_consolidated', 'VNS', 2018, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2016_consolidated', 'VNS', 2016, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2017_parent', 'VNS', 2017, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2015_consolidated', 'VNS', 2015, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2016_parent', 'VNS', 2016, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNS_2015_parent', 'VNS', 2015, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VNR_2025_parent', 'VNR', 2025, 'parent', 'Deloitte Vietnam', 'unqualified', 0, NULL),
('VNR_2025_consolidated', 'VNR', 2025, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNR_2023_parent', 'VNR', 2023, 'parent', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VNR_2024_consolidated', 'VNR', 2024, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VNR_2023_consolidated', 'VNR', 2023, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VNR_2022_consolidated', 'VNR', 2022, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VNR_2022_parent', 'VNR', 2022, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VNR_2021_parent', 'VNR', 2021, 'parent', 'PwC (Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội)', 'unqualified', 0, NULL),
('VNR_2020_consolidated', 'VNR', 2020, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VNR_2020_parent', 'VNR', 2020, 'parent', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VNR_2019_consolidated', 'VNR', 2019, 'consolidated', 'Deloitte', 'unqualified', 0, NULL),
('VNR_2019_parent', 'VNR', 2019, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2018_parent', 'VNR', 2018, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2018_consolidated', 'VNR', 2018, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2017_parent', 'VNR', 2017, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2016_consolidated', 'VNR', 2016, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2017_consolidated', 'VNR', 2017, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2015_parent', 'VNR', 2015, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNR_2016_parent', 'VNR', 2016, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VNP_2025_consolidated', 'VNP', 2025, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VNP_2025_parent', 'VNP', 2025, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VNP_2024_parent', 'VNP', 2024, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNP_2024_consolidated', 'VNP', 2024, 'consolidated', 'Công ty TNHH Kiểm Toán VACO', 'unqualified', 0, NULL),
('VNP_2023_parent', 'VNP', 2023, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VNP_2023_consolidated', 'VNP', 2023, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VACO', 'unqualified', 0, NULL),
('VNP_2022_consolidated', 'VNP', 2022, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VNP_2021_consolidated', 'VNP', 2021, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VNP_2019_parent', 'VNP', 2019, 'parent', 'AISC', 'qualified', 0, NULL),
('VNP_2020_consolidated', 'VNP', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học TP.HCM (AISC)', 'unqualified', 1, 'Đến thời điểm 31 tháng 12 năm 2020, nợ ngắn hạn đã vượt quá tài sản ngắn hạn với số tiền 17.782.201.367 VND và Công ty phát sinh lỗ lũy kế đến ngày 31 tháng 12 năm 2020 là 56.103.958.534 VND. Điều này gây nên quan ngại về khả năng tạo tiền của Công ty để thanh toán cho các khoản nợ đến hạn thanh toán.'),
('VNP_2019_consolidated', 'VNP', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học TP.HCM', 'qualified', 0, NULL),
('VNP_2018_consolidated', 'VNP', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học TP.HCM (AISC)', 'qualified', 0, NULL),
('VNP_2018_parent', 'VNP', 2018, 'parent', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học TP.HCM (AISC)', 'qualified', 0, NULL),
('VNP_2017_consolidated', 'VNP', 2017, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VNP_2017_parent', 'VNP', 2017, 'parent', 'Công ty TNHH Kiểm toán VACO', 'qualified', 1, 'Tại ngày báo cáo, nợ ngắn hạn đã vượt quá tài sản ngắn hạn với giá trị 55.841.710.985 đồng, lỗ lũy kế là 100.066.867.405 đồng (chiếm 52% vốn điều lệ thực tế đã góp). Điều này cho thấy dấu hiệu về khả năng thanh toán của Công ty có thể ảnh hưởng đến khả năng hoạt động liên tục. Ban lãnh đạo nhận định hoạt động và kết quả kinh doanh trong các năm tới sẽ tăng trưởng tốt hơn để bù đắp các khoản lỗ này và thanh toán các khoản nợ quá hạn, do đó Công ty vẫn tiếp tục hoạt động trong thời gian ít nhất 12 tháng tới.'),
('VNP_2016_consolidated', 'VNP', 2016, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VNP_2016_parent', 'VNP', 2016, 'parent', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VNM_2025_consolidated', 'VNM', 2025, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VNP_2015_consolidated', 'VNP', 2015, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VNM_2025_parent', 'VNM', 2025, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VNM_2024_parent', 'VNM', 2024, 'parent', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('VNM_2024_consolidated', 'VNM', 2024, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VNM_2023_parent', 'VNM', 2023, 'parent', 'KPMG', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VNM_2023_consolidated', 'VNM', 2023, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2022_consolidated', 'VNM', 2022, 'consolidated', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('VNM_2022_parent', 'VNM', 2022, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VNM_2021_consolidated', 'VNM', 2021, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2020_parent', 'VNM', 2020, 'parent', 'KPMG Limited Branch (Chi nhánh Công ty TNHH KPMG tại Thành phố Hồ Chí Minh)', 'unqualified', 0, NULL),
('VNM_2020_consolidated', 'VNM', 2020, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VNM_2021_parent', 'VNM', 2021, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VNM_2019_consolidated', 'VNM', 2019, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2018_consolidated', 'VNM', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2019_parent', 'VNM', 2019, 'parent', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('VNM_2016_parent', 'VNM', 2016, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2016_consolidated', 'VNM', 2016, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2018_parent', 'VNM', 2018, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2017_consolidated', 'VNM', 2017, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2015_parent', 'VNM', 2015, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNM_2015_consolidated', 'VNM', 2015, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VNM_2017_parent', 'VNM', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VNL_2025_consolidated', 'VNL', 2025, 'consolidated', 'RSM Vietnam Auditing & Consulting Company Limited', 'unqualified', 0, NULL),
('VNL_2022_consolidated', 'VNL', 2022, 'consolidated', 'RSM Vietnam', 'qualified', 0, NULL),
('VNL_2024_consolidated', 'VNL', 2024, 'consolidated', 'Công ty TNHH Kiểm toán & Tư vấn RSM Việt Nam', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
