PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('BID_2017_parent', 'BID', 2017, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2016_consolidated', 'BID', 2016, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2019_parent', 'BID', 2019, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2016_parent', 'BID', 2016, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2015_consolidated', 'BID', 2015, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('BID_2015_parent', 'BID', 2015, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('ACB_2025_consolidated', 'ACB', 2025, 'consolidated', 'Chi nhánh Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('ACB_2025_parent', 'ACB', 2025, 'parent', 'KPMG', 'unqualified', 0, NULL),
('ACB_2024_consolidated', 'ACB', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('ACB_2024_parent', 'ACB', 2024, 'parent', 'KPMG Limited Branch', 'unqualified', 0, NULL),
('ACB_2023_consolidated', 'ACB', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('ACB_2022_consolidated', 'ACB', 2022, 'consolidated', 'Công ty TNHH KPMG (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2022_parent', 'ACB', 2022, 'parent', 'Công ty TNHH KPMG (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2021_consolidated', 'ACB', 2021, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2021_parent', 'ACB', 2021, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2020_consolidated', 'ACB', 2020, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2020_parent', 'ACB', 2020, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2018_parent', 'ACB', 2018, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2018_consolidated', 'ACB', 2018, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2019_consolidated', 'ACB', 2019, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('ACB_2019_parent', 'ACB', 2019, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2017_parent', 'ACB', 2017, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('ACB_2016_consolidated', 'ACB', 2016, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('ACB_2016_parent', 'ACB', 2016, 'parent', 'Chi nhánh Công ty TNHH KPMG tại Thành phố Hồ Chí Minh', 'unqualified', 0, NULL),
('ACB_2015_parent', 'ACB', 2015, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('ACB_2015_consolidated', 'ACB', 2015, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VMS_2024_consolidated', 'VMS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMS_2023_consolidated', 'VMS', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMS_2025_consolidated', 'VMS', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMS_2021_consolidated', 'VMS', 2021, 'consolidated', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VMS_2022_consolidated', 'VMS', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VMS_2018_consolidated', 'VMS', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('VMS_2019_consolidated', 'VMS', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('VMS_2017_consolidated', 'VMS', 2017, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VMS_2015_consolidated', 'VMS', 2015, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VMK_2024_consolidated', 'VMK', 2024, 'consolidated', 'Chi nhánh Hà Nội - Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMG_2024_consolidated', 'VMG', 2024, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 1, 'Tại ngày 31/12/2024, các khoản nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn với số tiền là 5.685.301.990 VND, đồng thời, Công ty có khoản lỗ lũy kế với số tiền là 121.279.230.672 VND. Trong năm tài chính kết thúc cùng ngày, Công ty có kết quả kinh doanh lỗ với số tiền là 6.401.386.128 VND.'),
('VMG_2025_consolidated', 'VMG', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 1, 'Tại ngày 31/12/2025, Nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn với số tiền là 21.529.729.627 VND. Công ty đang chịu một khoản lỗ lũy kế đến ngày 31/12/2025 với số tiền là 147.426.723.246 VND, đồng thời khoản lỗ lũy kế này đã làm âm Vốn chủ sở hữu với số tiền là 12.868.769.704 VND. Những điều kiện này cho thấy sự tồn tại yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VMG_2022_consolidated', 'VMG', 2022, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 1, 'Tại ngày 31/12/2022, các khoản nợ ngắn hạn của Công ty vượt quá tài sản ngắn hạn số tiền 44.274.954.657 VND. Công ty có kết quả kinh doanh lỗ 28.970.660 VND và lưu chuyển tiền thuần từ hoạt động kinh doanh âm 11.276.526.375 VND. Công ty đang chịu khoản lỗ lũy kế 115.431.170.995 VND. Khả năng tiếp tục hoạt động trong vòng 12 tháng tới phụ thuộc vào khả năng tạo ra dòng tiền và tìm kiếm các khoản vay dài hạn.'),
('VMG_2021_consolidated', 'VMG', 2021, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 1, 'Tại ngày 31/12/2021, nợ ngắn hạn của Công ty đã vượt tài sản ngắn hạn với số tiền 43.065.009.895 VND. Lưu chuyển tiền thuần trong năm âm 2.681.352.138 VND. Khả năng tiếp tục hoạt động trong vòng 12 tháng tới phụ thuộc vào khả năng tạo ra dòng tiền và tìm kiếm các khoản vay dài hạn.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VMG_2020_consolidated', 'VMG', 2020, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'qualified', 1, 'Khoản lỗ lũy kế tại ngày 31 tháng 12 năm 2020 là 100.496.058.302 VND và nợ ngắn hạn vượt tài sản ngắn hạn 30.681.410.765 VND, dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VMG_2019_consolidated', 'VMG', 2019, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt (Vietland)', 'qualified', 1, 'Khoản lỗ lũy kế của Công ty tại ngày 31/12/2019 là 95.751.492.840 VND và nợ ngắn hạn đã vượt hơn tài sản ngắn hạn 9.868.174.673 VND, dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VMG_2018_consolidated', 'VMG', 2018, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'qualified', 1, 'Khoản lỗ lũy kế tại ngày 31 tháng 12 năm 2018 là 91.392.770.080 VND và cũng tại ngày này, nợ ngắn hạn của Công ty đã vượt hơn tài sản ngắn hạn một khoản là 23.844.312.516 VND. Vì vậy, khả năng tiếp tục hoạt động của Công ty phụ thuộc vào khả năng tạo ra nguồn tiền từ hoạt động kinh doanh và sự hỗ trợ tài chính từ chủ đầu tư của Công ty.'),
('VMG_2017_consolidated', 'VMG', 2017, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'qualified', 1, 'Khoản lỗ lũy kế tại ngày 31 tháng 12 năm 2017 cao và cũng tại ngày này, nợ ngắn hạn của Công ty đã vượt hơn tài sản ngắn hạn. Vì vậy, khả năng tiếp tục hoạt động của Công ty phụ thuộc vào khả năng tạo ra nguồn tiền từ hoạt động kinh doanh của Công ty.'),
('VMG_2016_consolidated', 'VMG', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Đất Việt (Vietland)', 'qualified', 1, 'Khoản lỗ lũy kế tại ngày 31/12/2016 là 95.393.010.460 VND; nợ ngắn hạn vượt hơn tài sản ngắn hạn 18.614.838.854 VND. Khả năng tiếp tục hoạt động của Công ty phụ thuộc vào khả năng tạo ra nguồn tiền từ hoạt động kinh doanh.'),
('VMG_2015_consolidated', 'VMG', 2015, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'qualified', 1, 'Tại ngày 31/12/2015, tổng nợ phải trả ngắn hạn vượt quá tổng tài sản ngắn hạn 14.472.174.883 VND, khoản lỗ lũy kế là 89.676.463.461 VND chiếm 93% vốn điều lệ. Sự tồn tại không chắc chắn trọng yếu về khả năng Công ty tiếp tục hoạt động liên tục. Công ty phụ thuộc vào việc thu được lợi nhuận từ hoạt động trong tương lai hoặc thu xếp nguồn tài chính để trả nợ.'),
('VMD_2025_consolidated', 'VMD', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VMC_2024_consolidated', 'VMC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VMC_2023_consolidated', 'VMC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VMC_2025_consolidated', 'VMC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VMC_2023_parent', 'VMC', 2023, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VMC_2022_consolidated', 'VMC', 2022, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VMC_2021_parent', 'VMC', 2021, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMC_2021_consolidated', 'VMC', 2021, 'consolidated', 'Công ty Trách nhiệm hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMC_2020_parent', 'VMC', 2020, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMC_2020_consolidated', 'VMC', 2020, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VMC_2018_consolidated', 'VMC', 2018, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VMC_2019_parent', 'VMC', 2019, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VMC_2018_parent', 'VMC', 2018, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VMC_2017_consolidated', 'VMC', 2017, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VMC_2019_consolidated', 'VMC', 2019, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VMC_2016_consolidated', 'VMC', 2016, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VMC_2017_parent', 'VMC', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VMC_2015_consolidated', 'VMC', 2015, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VMA_2024_consolidated', 'VMA', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VMA_2025_consolidated', 'VMA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VMA_2023_consolidated', 'VMA', 2023, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VMA_2021_consolidated', 'VMA', 2021, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VMA_2020_consolidated', 'VMA', 2020, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VMA_2019_consolidated', 'VMA', 2019, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2019, tài sản ngắn hạn của Công ty là 128.291.741.137 đồng, nợ ngắn hạn của Công ty là 131.224.805.464 đồng, theo đó nợ ngắn hạn của Công ty tại ngày 31 tháng 12 năm 2019 đã vượt tài sản ngắn hạn của Công ty là 2.933.064.327 đồng.'),
('VMA_2018_consolidated', 'VMA', 2018, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VMA_2017_consolidated', 'VMA', 2017, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VMA_2016_consolidated', 'VMA', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY ACA', 'unqualified', 0, NULL),
('VMA_2015_consolidated', 'VMA', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY ACA', 'unqualified', 0, NULL),
('VLW_2025_consolidated', 'VLW', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế - Thành viên Hãng Kiểm toán Quốc tế AGN International', 'unqualified', 0, NULL),
('VLW_2023_consolidated', 'VLW', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế - Chi nhánh Sài Gòn', 'unqualified', 0, NULL),
('VLW_2022_consolidated', 'VLW', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế', 'unqualified', 0, NULL),
('VLW_2024_consolidated', 'VLW', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (ICPA) - Chi nhánh Sài Gòn', 'unqualified', 0, NULL),
('VLW_2021_consolidated', 'VLW', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLW_2020_consolidated', 'VLW', 2020, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VLW_2017_consolidated', 'VLW', 2017, 'consolidated', 'Công ty TNHH Kiểm toán CPA Vietnam', 'unqualified', 0, NULL),
('VLS_2025_consolidated', 'VLS', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VLS_2024_consolidated', 'VLS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế INPACT', 'unqualified', 0, NULL),
('VLP_2024_consolidated', 'VLP', 2024, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VLP_2023_consolidated', 'VLP', 2023, 'consolidated', 'Công ty TNHH Kiểm Toán AFC Việt Nam - Chi nhánh Cần Thơ', 'unqualified', 0, NULL),
('VLP_2025_consolidated', 'VLP', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VLP_2022_consolidated', 'VLP', 2022, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam – Chi nhánh Cần Thơ', 'unqualified', 0, NULL),
('VLP_2021_consolidated', 'VLP', 2021, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh TP. Hồ Chí Minh', 'unqualified', 0, NULL),
('VLP_2019_consolidated', 'VLP', 2019, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VLP_2020_consolidated', 'VLP', 2020, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Chi nhánh TP. Hồ Chí Minh', 'unqualified', 0, NULL),
('VLP_2018_consolidated', 'VLP', 2018, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VLP_2017_consolidated', 'VLP', 2017, 'consolidated', 'Công ty TNHH Kiểm toán Sao Việt', 'qualified', 0, NULL),
('VLG_2025_consolidated', 'VLG', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VLG_2024_consolidated', 'VLG', 2024, 'consolidated', 'UHY Auditing and Consulting Limited Company', 'unqualified', 0, NULL),
('VLG_2023_consolidated', 'VLG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VLG_2022_consolidated', 'VLG', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLG_2021_consolidated', 'VLG', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLG_2020_consolidated', 'VLG', 2020, 'consolidated', 'Công ty TNHH Kiểm Toán AASC', 'unqualified', 0, NULL),
('VLG_2019_consolidated', 'VLG', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam (AVA)', 'unqualified', 0, NULL),
('VLG_2018_consolidated', 'VLG', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VLG_2017_consolidated', 'VLG', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLG_2016_consolidated', 'VLG', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLC_2025_consolidated', 'VLC', 2025, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLG_2015_consolidated', 'VLG', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLC_2024_parent', 'VLC', 2024, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2024_consolidated', 'VLC', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2023_consolidated', 'VLC', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2023_parent', 'VLC', 2023, 'parent', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VLC_2022_consolidated', 'VLC', 2022, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VLC_2022_parent', 'VLC', 2022, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2021_consolidated', 'VLC', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2021_parent', 'VLC', 2021, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VLC_2020_parent', 'VLC', 2020, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VLC_2020_consolidated', 'VLC', 2020, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VLC_2018_parent', 'VLC', 2018, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLC_2017_parent', 'VLC', 2017, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLC_2017_consolidated', 'VLC', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLC_2018_consolidated', 'VLC', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLC_2016_consolidated', 'VLC', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLC_2015_consolidated', 'VLC', 2015, 'consolidated', 'Công ty TNHH Hằng Kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VLB_2025_consolidated', 'VLB', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLC_2015_parent', 'VLC', 2015, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VLB_2024_consolidated', 'VLB', 2024, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VLB_2023_consolidated', 'VLB', 2023, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'qualified', 0, NULL),
('VLB_2022_consolidated', 'VLB', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'qualified', 0, NULL),
('VLB_2021_consolidated', 'VLB', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLB_2020_consolidated', 'VLB', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLB_2019_consolidated', 'VLB', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLB_2017_consolidated', 'VLB', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VLA_2025_consolidated', 'VLA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VLA_2024_consolidated', 'VLA', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VLA_2023_consolidated', 'VLA', 2023, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2020_consolidated', 'VLA', 2020, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2022_consolidated', 'VLA', 2022, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2019_consolidated', 'VLA', 2019, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2018_consolidated', 'VLA', 2018, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2017_consolidated', 'VLA', 2017, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2016_consolidated', 'VLA', 2016, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VLA_2015_consolidated', 'VLA', 2015, 'consolidated', 'Công ty TNHH Kiểm toán ASC', 'unqualified', 0, NULL),
('VKC_2025_consolidated', 'VKC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt', 'disclaimer', 1, 'Tại ngày 31/12/2025, Công ty có khoản lỗ lũy kế sau thuế chưa phân phối là (511.326.921.089) đồng; khoản nợ ngắn hạn (526.632.058.999 đồng) lớn hơn tài sản ngắn hạn của Công ty (177.825.822.434 đồng) với số tiền là 348.806.236.565 đồng; các khoản nợ phải trả nợ vay, trái phiếu và lãi tiền vay, trái phiếu đã quá hạn thanh toán với tổng số tiền là 516.422.072.160 đồng và vốn chủ sở hữu âm (290.196.738.243 đồng).');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VKC_2024_consolidated', 'VKC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Chuẩn Việt', 'disclaimer', 1, 'Các điều kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động kinh doanh liên tục của Công ty.'),
('VJC_2025_parent', 'VJC', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VJC_2025_consolidated', 'VJC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VJC_2024_consolidated', 'VJC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VJC_2023_consolidated', 'VJC', 2023, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VJC_2024_parent', 'VJC', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VJC_2022_consolidated', 'VJC', 2022, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VJC_2022_parent', 'VJC', 2022, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VJC_2021_consolidated', 'VJC', 2021, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VJC_2021_parent', 'VJC', 2021, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VJC_2020_consolidated', 'VJC', 2020, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 1, 'Sự tồn tại của yếu tố không chắc chắn trọng yếu do ảnh hưởng của dịch COVID-19 đến hoạt động kinh doanh và dòng tiền của Tập đoàn, khiến việc đánh giá về hoạt động liên tục phụ thuộc vào khả năng tạo ra đủ tiền từ hoạt động kinh doanh và các giải pháp khác.'),
('VJC_2020_parent', 'VJC', 2020, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 1, 'Sự lan rộng của dịch COVID-19 đã ảnh hưởng nghiêm trọng đến hoạt động kinh doanh vận tải hàng không, dẫn đến lỗ gộp và dòng tiền giảm sút. Các yếu tố không chắc chắn về khả năng phục hồi nhu cầu đi lại và quy định hạn chế đi lại tạo ra rủi ro trọng yếu đối với giả định hoạt động liên tục.'),
('VJC_2019_consolidated', 'VJC', 2019, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 1, 'Đại dịch COVID-19 tác động nghiêm trọng đến hoạt động kinh doanh hàng không. Giá trị giả định hoạt động liên tục phụ thuộc vào khả năng tạo đủ dòng tiền từ vận tải hàng không và tài chính thương mại tàu bay. Các quy định hạn chế đi lại quốc gia và sự phục hồi nhu cầu đi lại đường hàng không cho thấy sự tồn tại yếu tố không chắc chắn có thể ảnh hưởng quan trọng đến khả năng hoạt động liên tục.'),
('VJC_2019_parent', 'VJC', 2019, 'parent', 'Chi nhánh Công ty TNHH KPMG tại Thành phố Hồ Chí Minh', 'unqualified', 1, 'Ý kiến kiểm toán không bị thay đổi. Kiểm toán viên lưu ý người đọc về Thuyết minh 38 về ảnh hưởng của dịch COVID-19 đến tình hình hoạt động kinh doanh sau niên độ. Giá trị của giả định hoạt động liên tục cơ bản phụ thuộc vào khả năng Công ty tạo ra đủ dòng tiền từ hoạt động kinh doanh vận tải hàng không và tài chính thương mại tàu bay. Sự ảnh hưởng của các quy định hạn chế đi lại và sự phục hồi nhu cầu đi lại bằng đường hàng không cho thấy sự tồn tại của yếu tố không chắc chắn có thể ảnh hưởng quan trọng đến khả năng hoạt động liên tục.'),
('VJC_2018_parent', 'VJC', 2018, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VJC_2018_consolidated', 'VJC', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VJC_2017_consolidated', 'VJC', 2017, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VJC_2017_parent', 'VJC', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VJC_2016_consolidated', 'VJC', 2016, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VJC_2016_parent', 'VJC', 2016, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VJC_2015_consolidated', 'VJC', 2015, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VJC_2015_parent', 'VJC', 2015, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VIX_2025_consolidated', 'VIX', 2025, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIX_2023_consolidated', 'VIX', 2023, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('VIX_2022_consolidated', 'VIX', 2022, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIX_2021_consolidated', 'VIX', 2021, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIX_2018_consolidated', 'VIX', 2018, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIX_2019_consolidated', 'VIX', 2019, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIW_2025_parent', 'VIW', 2025, 'parent', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2025_consolidated', 'VIW', 2025, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2024_consolidated', 'VIW', 2024, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 1, 'Tại ngày 31/12/2024, một số công ty con và công ty liên kết của Tổng công ty đang gặp khó khăn về tài chính. Kiểm toán viên không thể thu thập đầy đủ bằng chứng kiểm toán để đánh giá tính đầy đủ của dự phòng khoản phải thu khó đòi, dự phòng giảm giá hàng tồn kho và dự phòng đầu tư tài chính dài hạn.'),
('VIW_2023_consolidated', 'VIW', 2023, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2022_consolidated', 'VIW', 2022, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2021_consolidated', 'VIW', 2021, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2020_consolidated', 'VIW', 2020, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2020_parent', 'VIW', 2020, 'parent', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2019_consolidated', 'VIW', 2019, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2018_consolidated', 'VIW', 2018, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2018_parent', 'VIW', 2018, 'parent', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VIW_2017_parent', 'VIW', 2017, 'parent', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIW_2017_consolidated', 'VIW', 2017, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 1, 'Có nhiều vấn đề ảnh hưởng đến khả năng hoạt động liên tục: Công ty con Viwaseen.1 chưa ghi nhận khoản nợ thuế hơn 9.6 tỷ đồng; Công ty con Viwaseen.2 có sai lệch số dư thuế GTGT phải nộp; Không hợp nhất được Công ty Viwaseen.15 do tạm dừng hoạt động; Nhiều khoản phải thu, phải trả và chi phí sản xuất dở dang chưa được đối chiếu, xác nhận đầy đủ; Chưa hoàn tất quyết toán cổ phần hóa.'),
('VIW_2015_consolidated', 'VIW', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VIT_2025_consolidated', 'VIT', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIT_2024_consolidated', 'VIT', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIT_2023_consolidated', 'VIT', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIT_2022_consolidated', 'VIT', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIT_2020_consolidated', 'VIT', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Tại ngày 31/12/2020, Nợ ngắn hạn đã vượt quá Tài sản ngắn hạn là 41,09 tỷ VND. Công ty lập BCTC dựa trên giả định hoạt động liên tục do: (1) Tình hình xuất phát từ việc huy động vốn vay lớn đầu tư Nhà máy Viglacera Mỹ Đức đang dần phát huy hiệu quả; (2) Đại hội đồng Cổ đông thông qua phương án tăng vốn điều lệ từ 195 tỷ lên 500 tỷ đồng; (3) Công ty là công ty con của Tổng công ty Viglacera - CTCP nên được đảm bảo hỗ trợ tài chính.'),
('VIT_2021_consolidated', 'VIT', 2021, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIT_2019_consolidated', 'VIT', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIT_2018_consolidated', 'VIT', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIT_2016_consolidated', 'VIT', 2016, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIT_2017_consolidated', 'VIT', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIT_2015_consolidated', 'VIT', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VISECO_2025_consolidated', 'VISECO', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VISECO_2023_consolidated', 'VISECO', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 1, 'Năm 2023, Công ty tiếp tục bị lỗ 4.593.950.015 đồng, khoản lỗ lũy kế đến ngày 31/12/2023 là 13.697.508.353 đồng, lưu chuyển tiền thuần từ hoạt động kinh doanh tiếp tục bị âm. Các yếu tố này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục. Công ty đã có phương án tăng vốn điều lệ từ 37.500.000.000 đồng lên mức 337.500.000.000 đồng và Ban Tổng Giám đốc tiếp tục thực hiện các biện pháp quản lý chặt chẽ, xây dựng kế hoạch kinh doanh hợp lý.'),
('VISECO_2021_consolidated', 'VISECO', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh Miền Trung', 'unqualified', 0, NULL),
('VISECO_2024_consolidated', 'VISECO', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ tin học MOORE AISC', 'qualified', 0, NULL),
('VISECO_2020_consolidated', 'VISECO', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY – Chi nhánh Miền Trung', 'unqualified', 0, NULL),
('VISECO_2018_consolidated', 'VISECO', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VISECO_2019_consolidated', 'VISECO', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY – Chi nhánh Miền Trung', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
