PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSG_2017_consolidated', 'VSG', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 1, 'Công ty tiếp tục bị lỗ 50.327.941.689 VND và khoản lỗ lũy kế đến ngày 31 tháng 12 năm 2017 là 469.559.865.261 VND. Ngoài ra, tại ngày 31 tháng 12 năm 2017 các khoản nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn của Công ty là 522.763.369.563 VND.'),
('VSF_2025_consolidated', 'VSF', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế INPACT', 'unqualified', 0, NULL),
('VSG_2016_consolidated', 'VSG', 2016, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 1, 'Công ty tiếp tục bị lỗ 40,143,956,219 VND trong năm 2016, lỗ lũy kế 419,231,923,572 VND. Nợ ngắn hạn vượt quá tài sản ngắn hạn 511,392,257,412 VND. Công ty đang làm việc với ngân hàng để có kế hoạch trả nợ phù hợp.'),
('VSG_2015_consolidated', 'VSG', 2015, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 1, 'Công ty tiếp tục bị lỗ 91.725.417.358 VND và khoản lỗ lũy kế 379.087.967.353 VND. Nợ ngắn hạn vượt quá tài sản ngắn hạn 508.996.977.891 VND, nghi ngờ khả năng hoạt động liên tục.'),
('VSF_2023_consolidated', 'VSF', 2023, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VSF_2024_consolidated', 'VSF', 2024, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 1, 'Tổng Công ty đang chịu khoản lỗ lũy kế đến 31/12/2024 là 2.641.548.688.028 VND, dẫn đến thâm hụt vốn chủ sở hữu. Khả năng tiếp tục hoạt động phụ thuộc vào việc các tổ chức tín dụng cung cấp và duy trì đủ hạn mức tín dụng. Công ty đã triển khai Đề án tái cơ cấu được Ủy ban quản lý vốn Nhà nước phê duyệt theo Quyết định số 2902/UBQLV-NN ngày 29/12/2023.'),
('VSF_2023_parent', 'VSF', 2023, 'parent', 'CPA VIETNAM', 'unqualified', 1, 'Tổng Công ty đang chịu lỗ lũy kế 2.645.851.822.319 VND và thâm hụt vốn chủ sở hữu, dẫn đến phụ thuộc vào tín dụng ngân hàng để thanh toán nợ. Ban Tổng Giám đốc đã triển khai kế hoạch tái cơ cấu và tin tưởng hoạt động liên tục.'),
('VSF_2022_consolidated', 'VSF', 2022, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 0, NULL),
('VSF_2022_parent', 'VSF', 2022, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VTM_2018_consolidated', 'VTM', 2018, 'consolidated', 'Công Ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('WSB_2015_parent', 'WSB', 2015, 'parent', 'PricewaterhouseCoopers Vietnam', 'qualified', 0, NULL),
('XPH_2016_consolidated', 'XPH', 2016, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'unqualified', 0, NULL),
('VTJ_2021_parent', 'VTJ', 2021, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTD_2024_consolidated', 'VTD', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VSI_2022_parent', 'VSI', 2022, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VSM_2022_parent', 'VSM', 2022, 'parent', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VSF_2020_consolidated', 'VSF', 2020, 'consolidated', '', 'unqualified', 1, 'Công ty liên tục lỗ trong năm 2019 và 2020, lợi nhuận sau thuế âm, cho thấy nguy cơ về hoạt động liên tục.'),
('VSF_2019_consolidated', 'VSF', 2019, 'consolidated', 'KPMG', 'qualified', 1, NULL),
('VSF_2020_parent', 'VSF', 2020, 'parent', 'KPMG Việt Nam', 'unqualified', 1, 'Tổng Công ty có lỗ lũy kế lớn, nợ ngắn hạn vượt tài sản ngắn hạn 14,319 triệu VND, và các khoản vay đáng kể cần tái tài trợ. Giá trị giả định hoạt động liên tục phụ thuộc vào khả năng tạo đủ dòng tiền và duy trì hạn mức tín dụng từ các tổ chức tín dụng.'),
('VSF_2019_parent', 'VSF', 2019, 'parent', 'KPMG Việt Nam', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2019, nợ ngắn hạn đã vượt quá tài sản ngắn hạn 13.509 triệu VND và Tổng Công ty có các khoản vay đáng kể cần tái tài trợ trong vòng 12 tháng kế tiếp. Tuy nhiên, Ban Tổng Giám đốc tin rằng Tổng Công ty có thể tạo ra đủ dòng tiền từ hoạt động kinh doanh và tiếp tục sử dụng hạn mức tín dụng từ các tổ chức tín dụng để thanh toán các khoản nợ đến hạn và duy trì hoạt động liên tục.');
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSF_2021_parent', 'VSF', 2021, 'parent', 'Chi nhánh Công ty TNHH KPMG tại Thành phố Hồ Chí Minh', 'unqualified', 1, 'Nợ ngắn hạn đã vượt quá tài sản ngắn hạn là 101.790 triệu VND. Lỗ thuần sau thuế trong năm là 352.088 triệu VND, lưu chuyển tiền thuần từ hoạt động kinh doanh âm 273.977 triệu VND. Giá trị giả định hoạt động liên tục phụ thuộc vào việc các tổ chức tín dụng cung cấp và duy trì đủ hạn mức tín dụng.'),
('VSF_2018_consolidated', 'VSF', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VSF_2021_consolidated', 'VSF', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'qualified', 0, NULL),
('VSF_2017_parent', 'VSF', 2017, 'parent', 'Công ty TNHH Hăng Kiểm toán AASC', 'qualified', 0, NULL),
('VSF_2018_parent', 'VSF', 2018, 'parent', 'AASC', 'qualified', 0, NULL),
('VSE_2024_consolidated', 'VSE', 2024, 'consolidated', 'International Auditing and Valuation Company Limited', 'qualified', 0, NULL),
('VSE_2022_consolidated', 'VSE', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'qualified', 0, NULL),
('VSE_2025_consolidated', 'VSE', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Quốc tế', 'qualified', 0, NULL),
('VSE_2023_consolidated', 'VSE', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'qualified', 0, NULL),
('VSE_2018_consolidated', 'VSE', 2018, 'consolidated', 'Công ty TNHH Kiểm toán ASCO - Chi nhánh Hà Thành', 'qualified', 0, 'Báo cáo kiểm toán không đề cập rõ ràng về mối lo ngại hoạt động liên tục, nhưng có nêu vấn đề về các khoản phải thu khó đòi chưa trích lập dự phòng đầy đủ.'),
('VSE_2021_consolidated', 'VSE', 2021, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VÀ TƯ VẤN UHY', 'qualified', 0, NULL),
('VSC_2025_consolidated', 'VSC', 2025, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSC_2025_parent', 'VSC', 2025, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSE_2019_consolidated', 'VSE', 2019, 'consolidated', 'Công ty TNHH Kiểm toán ASCO - Chi nhánh Hà Thành', 'qualified', 0, NULL),
('VSC_2024_consolidated', 'VSC', 2024, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VSC_2023_consolidated', 'VSC', 2023, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VSC_2024_parent', 'VSC', 2024, 'parent', 'PwC Vietnam', 'unqualified', 0, NULL),
('VSC_2022_consolidated', 'VSC', 2022, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VSC_2023_parent', 'VSC', 2023, 'parent', 'PwC Vietnam', 'unqualified', 0, NULL),
('VSC_2022_parent', 'VSC', 2022, 'parent', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSC_2021_consolidated', 'VSC', 2021, 'consolidated', 'Chi nhánh Công ty TNHH PwC (Việt Nam) tại Hà Nội', 'unqualified', 0, NULL),
('VSC_2021_parent', 'VSC', 2021, 'parent', 'PwC Việt Nam', 'unqualified', 0, NULL),
('VSC_2020_consolidated', 'VSC', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSC_2019_consolidated', 'VSC', 2019, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSC_2020_parent', 'VSC', 2020, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VSC_2018_parent', 'VSC', 2018, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSC_2019_parent', 'VSC', 2019, 'parent', 'KPMG Limited', 'unqualified', 0, NULL),
('VSC_2018_consolidated', 'VSC', 2018, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VSC_2017_consolidated', 'VSC', 2017, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VSC_2016_parent', 'VSC', 2016, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSC_2016_consolidated', 'VSC', 2016, 'consolidated', 'KPMG Limited', 'unqualified', 0, NULL),
('VSC_2017_parent', 'VSC', 2017, 'parent', 'KPMG', 'unqualified', 0, NULL),
('VSC_2015_consolidated', 'VSC', 2015, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSC_2015_parent', 'VSC', 2015, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSA_2025_consolidated', 'VSA', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VSA_2017_consolidated', 'VSA', 2017, 'consolidated', 'KPMG Limited Branch in Ho Chi Minh City', 'unqualified', 0, NULL),
('VSA_2025_parent', 'VSA', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VSA_2017_parent', 'VSA', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSA_2024_consolidated', 'VSA', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VSA_2024_parent', 'VSA', 2024, 'parent', 'UHY Audit and Consulting Co., Ltd.', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VSA_2015_consolidated', 'VSA', 2015, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VSA_2015_parent', 'VSA', 2015, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VSA_2016_parent', 'VSA', 2016, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VSA_2016_consolidated', 'VSA', 2016, 'consolidated', 'Chi nhánh Công ty TNHH KPMG tại Thành phố Hồ Chí Minh', 'unqualified', 0, NULL),
('VRG_2025_consolidated', 'VRG', 2025, 'consolidated', 'MOORE AISC', 'unqualified', 0, NULL),
('VRG_2024_consolidated', 'VRG', 2024, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán và Dịch vụ Tin học MOORE AISC', 'unqualified', 0, NULL),
('VRG_2021_consolidated', 'VRG', 2021, 'consolidated', 'A&C Auditing and Consulting Co., Ltd. (Baker Tilly A&C)', 'qualified', 0, NULL),
('VRG_2023_consolidated', 'VRG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL),
('VRG_2019_consolidated', 'VRG', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'qualified', 0, NULL),
('VRG_2018_consolidated', 'VRG', 2018, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VRG_2017_consolidated', 'VRG', 2017, 'consolidated', 'Baker Tilly A&C', 'unqualified', 0, NULL),
('VRE_2025_consolidated', 'VRE', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VRG_2016_consolidated', 'VRG', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VRG_2015_consolidated', 'VRG', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VRE_2025_parent', 'VRE', 2025, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VRE_2024_consolidated', 'VRE', 2024, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VRE_2023_consolidated', 'VRE', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VRE_2024_parent', 'VRE', 2024, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VRE_2023_parent', 'VRE', 2023, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VRE_2022_consolidated', 'VRE', 2022, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VRE_2021_parent', 'VRE', 2021, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VRE_2021_consolidated', 'VRE', 2021, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VRE_2022_parent', 'VRE', 2022, 'parent', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VRE_2020_parent', 'VRE', 2020, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VRE_2020_consolidated', 'VRE', 2020, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VRE_2019_parent', 'VRE', 2019, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VRE_2018_consolidated', 'VRE', 2018, 'consolidated', 'KPMG', 'unqualified', 0, NULL),
('VRE_2019_consolidated', 'VRE', 2019, 'consolidated', 'KPMG Limited Branch in Ho Chi Minh City', 'unqualified', 0, NULL),
('VRE_2017_consolidated', 'VRE', 2017, 'consolidated', 'Công ty Trách nhiệm hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRE_2017_parent', 'VRE', 2017, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRE_2016_parent', 'VRE', 2016, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRE_2016_consolidated', 'VRE', 2016, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2025_consolidated', 'VRC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VRE_2015_parent', 'VRE', 2015, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRE_2015_consolidated', 'VRE', 2015, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2025_parent', 'VRC', 2025, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VRC_2024_parent', 'VRC', 2024, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VRC_2023_parent', 'VRC', 2023, 'parent', 'A&C Auditing and Consulting Co., Ltd. (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VRC_2024_consolidated', 'VRC', 2024, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VRC_2022_consolidated', 'VRC', 2022, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VRC_2022_parent', 'VRC', 2022, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VRC_2023_consolidated', 'VRC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VRC_2021_parent', 'VRC', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2020_consolidated', 'VRC', 2020, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2021_consolidated', 'VRC', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2020_parent', 'VRC', 2020, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2019_consolidated', 'VRC', 2019, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2018_consolidated', 'VRC', 2018, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2019_parent', 'VRC', 2019, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2018_parent', 'VRC', 2018, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VRC_2017_consolidated', 'VRC', 2017, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VRC_2017_parent', 'VRC', 2017, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VRC_2015_consolidated', 'VRC', 2015, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VRC_2015_parent', 'VRC', 2015, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VRC_2016_parent', 'VRC', 2016, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn Tài chính Quốc tế (IFC) - Chi nhánh TP. Hồ Chí Minh', 'unqualified', 0, NULL),
('VQC_2025_consolidated', 'VQC', 2025, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán AASC tại Quảng Ninh', 'unqualified', 0, NULL),
('VRC_2016_consolidated', 'VRC', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn Tài chính Quốc tế (IFC)', 'unqualified', 0, NULL),
('VQC_2023_consolidated', 'VQC', 2023, 'consolidated', 'Công ty TNHH Hãng kiểm toán AASC', 'unqualified', 0, NULL),
('VQC_2024_consolidated', 'VQC', 2024, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VQC_2018_consolidated', 'VQC', 2018, 'consolidated', 'Công ty TNHH Kiểm toán BDO', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VQC_2020_consolidated', 'VQC', 2020, 'consolidated', 'Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VQC_2021_consolidated', 'VQC', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VQC_2016_consolidated', 'VQC', 2016, 'consolidated', 'AASC Quảng Ninh', 'unqualified', 0, NULL),
('VQC_2019_consolidated', 'VQC', 2019, 'consolidated', 'Chỉ nhánh Công ty TNHH Hãng Kiểm toán AASC tại Quảng Ninh', 'unqualified', 0, NULL),
('VPX_2025_consolidated', 'VPX', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPW_2024_consolidated', 'VPW', 2024, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VQC_2015_consolidated', 'VQC', 2015, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPW_2025_consolidated', 'VPW', 2025, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VPW_2022_consolidated', 'VPW', 2022, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VACO', 'qualified', 0, NULL),
('VPW_2021_consolidated', 'VPW', 2021, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VPW_2019_consolidated', 'VPW', 2019, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VPW_2020_consolidated', 'VPW', 2020, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VPW_2017_consolidated', 'VPW', 2017, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 1, 'Kiểm toán viên không thể thu thập đầy đủ bằng chứng kiểm toán về tính chính xác của giá trị tài sản cố định - Nhà máy nước Yên Lạc (11.672.368.775 VND) và khoản phải trả khác dài hạn tương ứng. Công ty cũng chưa ghi nhận chi phí khấu hao của nhà máy này.'),
('VPW_2016_consolidated', 'VPW', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam', 'qualified', 0, NULL),
('VPS_2025_consolidated', 'VPS', 2025, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VPW_2018_consolidated', 'VPW', 2018, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VPS_2024_parent', 'VPS', 2024, 'parent', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 1, 'Công ty Cổ phần Thuốc sát trùng Việt Nam khởi kiện Nhà đầu tư MosFly International SDN.BHD liên quan đến Công ty liên kết Công ty TNHH Mosfly Việt Nam Industries (MVI) đang tạm ngừng hoạt động. Bản án số 32/2024/KDTM-PT ngày 12/06/2024 của Tòa án nhân dân cấp cao tại TP. Hồ Chí Minh không chấp nhận một phần yêu cầu khởi kiện.'),
('VPS_2025_parent', 'VPS', 2025, 'parent', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VPS_2024_consolidated', 'VPS', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2023_consolidated', 'VPS', 2023, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPS_2022_consolidated', 'VPS', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2023_parent', 'VPS', 2023, 'parent', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VPS_2022_parent', 'VPS', 2022, 'parent', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VPS_2021_consolidated', 'VPS', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Tại Công ty TNHH Mosfly Việt Nam Industries (MVI), kể từ thời điểm 31/03/2021, nợ phải trả ngắn hạn vượt quá tài sản ngắn hạn; Phần lớn các khoản phải trả của MVI đã quá hạn thanh toán và chưa có nguồn để hoàn trả; Nhà đầu tư Mosfly International SDN. BHD. (MISB) đã thu hồi lại thương hiệu Mosfly. Đồng thời, trong năm, MVI còn đang giải quyết nhiều đơn khởi kiện của các nhà cung cấp và người lao động.'),
('VPS_2021_parent', 'VPS', 2021, 'parent', 'Công ty TNHH Hằng Kiểm toán AASC', 'unqualified', 1, 'Tại Công ty TNHH Mosfly Việt Nam Industries (MVI), kể từ thời điểm 31/03/2021, nợ phải trả ngắn hạn vượt quá tài sản ngắn hạn; Phần lớn các khoản phải trả của MVI đã quá hạn thanh toán và chưa có nguồn để hoàn trả; Nhà đầu tư Mosfly International SDN. BHD. (MISB) đã thu hồi lại thương hiệu Mosfly. Đồng thời, trong năm, MVI còn đang giải quyết nhiều đơn khởi kiện của các nhà cung cấp và người lao động. Những sự kiện trên cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của MVI.'),
('VPS_2019_consolidated', 'VPS', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Công ty TNHH Sản xuất Nông dược Vi sinh Viguato (công ty con) có nguy cơ không hoạt động liên tục do Giấy chứng nhận đăng ký đầu tư hết hạn ngày 31/12/2019, phải di dời đến Khu công nghiệp tỉnh Sóc Trăng, giảm lao động từ 41 xuống 13 người, và chưa có kế hoạch sản xuất kinh doanh cụ thể. Báo cáo tài chính vẫn được hợp nhất dựa trên giả định hoạt động liên tục.'),
('VPS_2018_consolidated', 'VPS', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2019_parent', 'VPS', 2019, 'parent', 'AASC', 'unqualified', 0, NULL),
('VPS_2017_consolidated', 'VPS', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2018_parent', 'VPS', 2018, 'parent', 'AASC', 'unqualified', 0, NULL),
('VPS_2017_parent', 'VPS', 2017, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2016_consolidated', 'VPS', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPS_2016_parent', 'VPS', 2016, 'parent', 'AASC', 'unqualified', 0, NULL),
('VPS_2015_consolidated', 'VPS', 2015, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VPS_2015_parent', 'VPS', 2015, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VPR_2024_consolidated', 'VPR', 2024, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VPR_2025_consolidated', 'VPR', 2025, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VPR_2020_consolidated', 'VPR', 2020, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VPR_2017_consolidated', 'VPR', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VPR_2021_consolidated', 'VPR', 2021, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPR_2019_consolidated', 'VPR', 2019, 'consolidated', 'A&C Auditing and Consulting Co., Ltd. (Công ty TNHH Kiểm toán và Tư vấn A&C - Baker Tilly A&C)', 'unqualified', 0, NULL),
('VPR_2015_consolidated', 'VPR', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'qualified', 0, 'Khoản chi phí xây dựng cơ bản dở dang của công trình cao ốc Thị Nghề và dự án Phú Lâm do công trình đã tạm ngừng không thực hiện từ năm 2008 với tổng số tiền là 1.340.924.720 VND.'),
('VPR_2018_consolidated', 'VPR', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VPL_2025_consolidated', 'VPL', 2025, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPL_2024_consolidated', 'VPL', 2024, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPL_2024_parent', 'VPL', 2024, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPL_2023_parent', 'VPL', 2023, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 1, 'Tính phù hợp của giả định hoạt động liên tục... cơ bản tùy thuộc vào việc công ty mẹ của Công ty, Tập đoàn Vingroup – Công ty CP, tiếp tục cung cấp các hỗ trợ tài chính cần thiết nhằm giúp Công ty có thể thanh toán các khoản nợ phải trả khi đến hạn... Tại thời điểm lập báo cáo này, Tập đoàn Vingroup – Công ty CP đã xác nhận rằng Tập đoàn sẽ tiếp tục cung cấp các hỗ trợ tài chính cần thiết để đảm bảo khả năng hoạt động liên tục của Công ty.'),
('VPL_2025_parent', 'VPL', 2025, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPL_2018_consolidated', 'VPL', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VPL_2017_consolidated', 'VPL', 2017, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPL_2023_consolidated', 'VPL', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VPL_2018_parent', 'VPL', 2018, 'parent', 'KPMG Limited (Công ty TNHH KPMG Việt Nam)', 'unqualified', 0, NULL),
('VPL_2017_parent', 'VPL', 2017, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2024_consolidated', 'VPI', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2025_parent', 'VPI', 2025, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2025_consolidated', 'VPI', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2024_parent', 'VPI', 2024, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2023_consolidated', 'VPI', 2023, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2023_parent', 'VPI', 2023, 'parent', 'Công ty TNHH Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('VPI_2021_consolidated', 'VPI', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VPI_2022_parent', 'VPI', 2022, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2022_consolidated', 'VPI', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2021_parent', 'VPI', 2021, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2020_parent', 'VPI', 2020, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2020_consolidated', 'VPI', 2020, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VPI_2019_parent', 'VPI', 2019, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPI_2019_consolidated', 'VPI', 2019, 'consolidated', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VPI_2018_consolidated', 'VPI', 2018, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VPI_2017_parent', 'VPI', 2017, 'parent', 'AFC Vietnam Auditing Co., Ltd.', 'unqualified', 0, NULL),
('VPI_2017_consolidated', 'VPI', 2017, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('VPI_2016_consolidated', 'VPI', 2016, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('VPI_2016_parent', 'VPI', 2016, 'parent', 'Công ty TNHH Kiểm Toán AFC Việt Nam - Chi nhánh Phía Bắc', 'unqualified', 0, NULL),
('VPI_2018_parent', 'VPI', 2018, 'parent', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VPH_2025_consolidated', 'VPH', 2025, 'consolidated', 'Công ty TNHH Kiểm Toán VACO', 'unqualified', 0, NULL),
('VPH_2025_parent', 'VPH', 2025, 'parent', 'Công ty TNHH Kiểm Toán VACO – Chi nhánh TP.HCM', 'unqualified', 0, NULL),
('VPH_2024_parent', 'VPH', 2024, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VPH_2023_consolidated', 'VPH', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP.HCM', 'unqualified', 1, 'Tại ngày 31/12/2023, tổng tài sản ngắn hạn trên Báo cáo tài chính riêng của Công ty mẹ đang thấp hơn nợ phải trả ngắn hạn số tiền là 542.322.875.647 đồng, chủ yếu là do các khoản vay tổ chức và các cá nhân, đồng thời dòng tiền từ hoạt động kinh doanh chính của Công ty trên cả Báo cáo tài chính riêng và hợp nhất đều bị âm.'),
('VPH_2024_consolidated', 'VPH', 2024, 'consolidated', 'Công ty TNHH Kiểm toán VACO - Chi nhánh Thành phố Hồ Chí Minh', 'unqualified', 0, NULL),
('VPH_2022_parent', 'VPH', 2022, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn UHY - Chi nhánh tại TP.HCM', 'unqualified', 0, NULL),
('VPH_2023_parent', 'VPH', 2023, 'parent', 'UHY Vietnam', 'unqualified', 1, 'Tại ngày 31/12/2023, tổng tài sản ngắn hạn của Công ty đang thấp hơn nợ phải trả ngắn hạn số tiền là 542.322.875.647 đồng, chủ yếu là do các khoản vay tổ chức và các cá nhân, đồng thời dòng tiền từ hoạt động kinh doanh chính của Công ty bị âm.');
PRAGMA foreign_keys = ON;
