PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VISECO_2017_consolidated', 'VISECO', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VISECO_2016_consolidated', 'VISECO', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY ACA', 'unqualified', 0, NULL),
('VIR_2024_consolidated', 'VIR', 2024, 'consolidated', 'Công ty TNHH Kiểm toán FAC - Chi nhánh Đệ Nhất', 'disclaimer', 1, 'Công ty bị cưỡng chế thu hồi đất, phá dỡ toàn bộ tài sản kinh doanh tại khu vực bãi tắm đường Thùy Vân, TP. Vũng Tàu; Ban Giám đốc chưa có kế hoạch phục hồi cụ thể; không thu thập đủ bằng chứng để đánh giá giả định hoạt động liên tục.'),
('VIR_2022_consolidated', 'VIR', 2022, 'consolidated', 'Công ty TNHH Kiểm toán FAC - Chi nhánh Đệ Nhất', 'disclaimer', 1, 'Kiểm toán viên không thể thu thập đủ bằng chứng kiểm toán do Công ty chưa được ký kết hợp đồng thuê đất, thuê cơ sở hạ tầng, và có tranh chấp, khiếu nại liên quan đến tiền thuê đất, cơ sở hạ tầng bị truy thu (tổng số tiền 38,469,784,319 VND), dẫn đến nghi ngờ về khả năng hoạt động liên tục.'),
('VIR_2025_consolidated', 'VIR', 2025, 'consolidated', 'Công ty TNHH Kiểm toán FAC - Chi nhánh Đệ Nhất', 'disclaimer', 1, 'Công ty bị thu hồi đất tại Vũng Tàu Intourco Resort, dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VIR_2021_consolidated', 'VIR', 2021, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'disclaimer', 0, NULL),
('VIR_2020_consolidated', 'VIR', 2020, 'consolidated', 'Công ty TNHH Kiểm toán FAC - Chi nhánh Đệ Nhất', 'disclaimer', 0, NULL),
('VIR_2019_consolidated', 'VIR', 2019, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'disclaimer', 1, 'Thanh tra tỉnh ban hành Kết luận số 261/KL-TTr về việc thu hồi tiền thuê đất (34.490.774.319 VND) và tiền thuê hạ tầng kỹ thuật (3.979.010.000 VND) tại Bãi Thủy Vân. Công ty chưa được cơ quan có thẩm quyền ký hợp đồng cho thuê đất/hạ tầng, chưa thống nhất giá thuê, chi phí ghi nhận thiếu chưa xác định được. Công ty đang kiến nghị xem xét lại. Kiểm toán viên không thu thập đủ bằng chứng kiểm toán nên từ chối đưa ra ý kiến.'),
('VIR_2018_consolidated', 'VIR', 2018, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'disclaimer', 0, NULL),
('VIR_2016_consolidated', 'VIR', 2016, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'unqualified', 0, NULL),
('VIR_2015_consolidated', 'VIR', 2015, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'unqualified', 0, NULL),
('VIR_2017_consolidated', 'VIR', 2017, 'consolidated', 'Công ty TNHH Kiểm toán FAC - Chi nhánh Đệ Nhất', 'unqualified', 0, NULL),
('VIP_2025_parent', 'VIP', 2025, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2024_consolidated', 'VIP', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2025_consolidated', 'VIP', 2025, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2024_parent', 'VIP', 2024, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2023_consolidated', 'VIP', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2023_parent', 'VIP', 2023, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2022_consolidated', 'VIP', 2022, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2021_consolidated', 'VIP', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIP_2022_parent', 'VIP', 2022, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2020_parent', 'VIP', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2021_parent', 'VIP', 2021, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2020_consolidated', 'VIP', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2019_consolidated', 'VIP', 2019, 'consolidated', 'Công ty TNHH KPMG', 'unqualified', 0, NULL),
('VIP_2019_parent', 'VIP', 2019, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2018_consolidated', 'VIP', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2018_parent', 'VIP', 2018, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2016_consolidated', 'VIP', 2016, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2016_parent', 'VIP', 2016, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2015_parent', 'VIP', 2015, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('Vinphaco_2025_consolidated', 'Vinphaco', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VIP_2015_consolidated', 'VIP', 2015, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIP_2017_parent', 'VIP', 2017, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIP_2017_consolidated', 'VIP', 2017, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIN_2024_parent', 'VIN', 2024, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2024_consolidated', 'VIN', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VIN_2023_consolidated', 'VIN', 2023, 'consolidated', 'Công ty TNHH AASC', 'qualified', 0, NULL),
('VIN_2023_parent', 'VIN', 2023, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2022_consolidated', 'VIN', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIN_2021_consolidated', 'VIN', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2021_parent', 'VIN', 2021, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2022_parent', 'VIN', 2022, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2020_parent', 'VIN', 2020, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2020_consolidated', 'VIN', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2019_consolidated', 'VIN', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2019_parent', 'VIN', 2019, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2018_consolidated', 'VIN', 2018, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2017_consolidated', 'VIN', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2018_parent', 'VIN', 2018, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2017_parent', 'VIN', 2017, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2016_parent', 'VIN', 2016, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2016_consolidated', 'VIN', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2015_consolidated', 'VIN', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIN_2015_parent', 'VIN', 2015, 'parent', 'Công ty TNHH Hàng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIM_2025_consolidated', 'VIM', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIM_2024_consolidated', 'VIM', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIM_2022_consolidated', 'VIM', 2022, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIM_2020_consolidated', 'VIM', 2020, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('VIM_2019_consolidated', 'VIM', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VikkiBankS_2025_consolidated', 'VikkiBankS', 2025, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'qualified', 0, NULL),
('VIM_2018_consolidated', 'VIM', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIH_2024_consolidated', 'VIH', 2024, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIH_2025_consolidated', 'VIH', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIH_2023_consolidated', 'VIH', 2023, 'consolidated', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIH_2020_consolidated', 'VIH', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VIH_2021_consolidated', 'VIH', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIH_2019_consolidated', 'VIH', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Báo cáo tài chính vẫn được trình bày dựa trên cơ sở giả định hoạt động liên tục vì Công ty là Công ty con của Tổng Công ty Viglacera - CTCP nên vẫn duy trì được sự hỗ trợ về tài chính, nguồn lực, công nghệ; dây chuyền sản xuất gạch bán sứ hoạt động ổn định, sản phẩm đầu ra tiêu thụ tăng cao, kinh doanh tiếp tục có lãi và lợi nhuận lũy kế tăng dần; Công ty dự kiến đảm bảo cân đối đủ vốn lưu động phục vụ hoạt động kinh doanh.'),
('VIH_2017_consolidated', 'VIH', 2017, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIE_2025_consolidated', 'VIE', 2025, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIH_2018_consolidated', 'VIH', 2018, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 1, 'Báo cáo tài chính đang phản ánh tổng số nợ ngắn hạn lớn hơn tài sản ngắn hạn là 90,76 tỷ VND. Tuy nhiên, Công ty vẫn trình bày trên cơ sở giả định hoạt động liên tục do được sự hỗ trợ tài chính từ Tổng Công ty Viglacera - CTCP (công ty mẹ), dây chuyền sản xuất gạch bán sứ đã hoạt động ổn định, sản phẩm tiêu thụ tăng cao, và Công ty dự kiến đảm bảo cân đối đủ vốn lưu động.'),
('VIE_2023_consolidated', 'VIE', 2023, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2024_consolidated', 'VIE', 2024, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2022_consolidated', 'VIE', 2022, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2021_consolidated', 'VIE', 2021, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2020_consolidated', 'VIE', 2020, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2018_consolidated', 'VIE', 2018, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2017_consolidated', 'VIE', 2017, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VIE_2016_consolidated', 'VIE', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VIE_2019_consolidated', 'VIE', 2019, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIE_2015_consolidated', 'VIE', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'qualified', 0, NULL),
('VIF_2024_parent', 'VIF', 2024, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2024_consolidated', 'VIF', 2024, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2025_consolidated', 'VIF', 2025, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2023_consolidated', 'VIF', 2023, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam - Chi nhánh Hà Nội', 'unqualified', 0, NULL),
('VIF_2022_consolidated', 'VIF', 2022, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2022_parent', 'VIF', 2022, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('ACB_2017_consolidated', 'ACB', 2017, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('CTG_2021_parent', 'CTG', 2021, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIG_2025_consolidated', 'VIG', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Quốc tế', 'unqualified', 0, NULL),
('VIG_2024_consolidated', 'VIG', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VIG_2023_consolidated', 'VIG', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VIM_2021_consolidated', 'VIM', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIG_2021_consolidated', 'VIG', 2021, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'unqualified', 1, 'Lỗ lũy kế âm 167,28 tỷ đồng, hoạt động cầm chừng. Công ty TNHH MTV Đầu tư và Phát triển Nông nghiệp Hà Nội (Handico) yêu cầu thanh toán toàn bộ nợ gốc và lãi, đe dọa thủ tục phá sản nếu không thanh toán. Công ty chưa có phương án hay nguồn tiền để trả nợ.'),
('VIG_2022_consolidated', 'VIG', 2022, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY', 'unqualified', 0, NULL),
('VIG_2019_consolidated', 'VIG', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Lỗ lũy kế âm 165,2 tỷ đồng, hoạt động cầm chung, có nghi ngờ đáng kể về khả năng hoạt động liên tục.'),
('VIG_2017_consolidated', 'VIG', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Tại thời điểm 31/12/2017, lỗ lũy kế trên báo cáo tình hình tài chính của Công ty là âm 142,89 tỷ đồng, hoạt động của Công ty duy trì ở mức độ cầm chừng. Sự kiện này cho thấy có yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty. Tuy nhiên, báo cáo tài chính vẫn được lập trên cơ sở giả định hoạt động liên tục do năm 2017 Công ty hoạt động có lãi và lưu chuyển tiền thuần từ hoạt động kinh doanh dương.'),
('VIG_2018_consolidated', 'VIG', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Tại thời điểm 31/12/2018, lỗ lũy kế trên báo cáo tình hình tài chính của Công ty là âm 141,26 tỷ đồng. Hoạt động của Công ty duy trì ở mức độ cầm chừng. Sự kiện này cho thấy có yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục. Tuy nhiên, hoạt động kinh doanh trong năm có lãi, lưu chuyển tiền thuần từ hoạt động kinh doanh dương, và Công ty có kế hoạch mở rộng cơ sở kinh doanh, phát triển thêm khách hàng trong năm tới. Báo cáo tài chính vẫn được lập trên cơ sở giả định về hoạt động liên tục.'),
('VIG_2015_consolidated', 'VIG', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIG_2016_consolidated', 'VIG', 2016, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIF_2025_parent', 'VIF', 2025, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2021_consolidated', 'VIF', 2021, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIG_2020_consolidated', 'VIG', 2020, 'consolidated', 'Công ty TNHH Kiểm toán - Tư vấn Đất Việt', 'unqualified', 1, 'Lỗ lũy kế âm 168,71 tỷ đồng; lưu chuyển tiền thuần từ hoạt động kinh doanh âm 0,6 tỷ đồng; hoạt động Công ty duy trì ở mức cầm chưng. Kiểm toán viên cho thấy có yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty. Báo cáo tài chính vẫn được lập trên cơ sở giả định về hoạt động liên tục.'),
('VIF_2021_parent', 'VIF', 2021, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2020_consolidated', 'VIF', 2020, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2020_parent', 'VIF', 2020, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2019_consolidated', 'VIF', 2019, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2018_consolidated', 'VIF', 2018, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIF_2019_parent', 'VIF', 2019, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2018_parent', 'VIF', 2018, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VIF_2016_consolidated', 'VIF', 2016, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2017_consolidated', 'VIF', 2017, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2017_parent', 'VIF', 2017, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIF_2015_consolidated', 'VIF', 2015, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'qualified', 0, 'Công ty con - Công ty Cổ phần Vinafor Tây Nguyên được kiểm toán với ý kiến ''Từ chối đưa ra ý kiến''. Kiểm toán viên không thể đánh giá tính hiện hữu và đầy đủ của hàng tồn kho (34,8 tỷ VND) và các khoản công nợ phải thu (53,1 tỷ VND), phải trả (48,6 tỷ VND) chưa được đối chiếu xác nhận tại đơn vị này.'),
('VIDBank_2025_consolidated', 'VIDBank', 2025, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIF_2015_parent', 'VIF', 2015, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VIDBank_2025_parent', 'VIDBank', 2025, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIDBank_2024_consolidated', 'VIDBank', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIDBank_2024_parent', 'VIDBank', 2024, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VID_2025_parent', 'VID', 2025, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VID_2025_consolidated', 'VID', 2025, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Phía Nam (AASCS)', 'unqualified', 0, NULL),
('VID_2024_consolidated', 'VID', 2024, 'consolidated', 'Công ty TNHH Kiểm toán FAC', 'unqualified', 0, NULL),
('VID_2024_parent', 'VID', 2024, 'parent', 'Công ty TNHH Kiểm toán FAC', 'unqualified', 0, NULL),
('VID_2023_consolidated', 'VID', 2023, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VID_2023_parent', 'VID', 2023, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VID_2022_parent', 'VID', 2022, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2022_consolidated', 'VID', 2022, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2021_consolidated', 'VID', 2021, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2020_consolidated', 'VID', 2020, 'consolidated', 'Công ty TNHH PKF Việt Nam, Chi nhánh Thành phố Hồ Chí Minh', 'unqualified', 0, NULL),
('VID_2021_parent', 'VID', 2021, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2019_consolidated', 'VID', 2019, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2020_parent', 'VID', 2020, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2018_consolidated', 'VID', 2018, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2019_parent', 'VID', 2019, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2018_parent', 'VID', 2018, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2017_consolidated', 'VID', 2017, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2017_parent', 'VID', 2017, 'parent', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VID_2016_consolidated', 'VID', 2016, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'qualified', 0, NULL),
('VID_2016_parent', 'VID', 2016, 'parent', 'Công ty TNHH PKF Việt Nam', 'qualified', 0, NULL),
('VIC_2025_consolidated', 'VIC', 2025, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIC_2025_parent', 'VIC', 2025, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2024_consolidated', 'VIC', 2024, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2024_parent', 'VIC', 2024, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2023_consolidated', 'VIC', 2023, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam – Chi nhánh Hà Nội', 'unqualified', 1, 'Tập đoàn có khoản lỗ thuần từ hoạt động kinh doanh là 4.905 tỷ VND và lưu chuyển tiền thuần từ hoạt động kinh doanh âm trong năm 2023. Tại ngày 31 tháng 12 năm 2023, nợ ngắn hạn vượt quá tài sản ngắn hạn 57.762 tỷ VND. Khả năng hoạt động liên tục phụ thuộc vào việc hoàn thành các kế hoạch kinh doanh và tài chính đã được đề ra, bao gồm dòng tiền dự kiến từ các dự án, tái cơ cấu đầu tư và kế hoạch huy động vốn.'),
('VIC_2023_parent', 'VIC', 2023, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2022_parent', 'VIC', 2022, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2022_consolidated', 'VIC', 2022, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2021_parent', 'VIC', 2021, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2021_consolidated', 'VIC', 2021, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2020_consolidated', 'VIC', 2020, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2020_parent', 'VIC', 2020, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2019_parent', 'VIC', 2019, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2018_consolidated', 'VIC', 2018, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2019_consolidated', 'VIC', 2019, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2017_consolidated', 'VIC', 2017, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2018_parent', 'VIC', 2018, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2017_parent', 'VIC', 2017, 'parent', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VIC_2016_consolidated', 'VIC', 2016, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2016_parent', 'VIC', 2016, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIC_2015_consolidated', 'VIC', 2015, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIC_2015_parent', 'VIC', 2015, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2025_parent', 'VIB', 2025, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2025_consolidated', 'VIB', 2025, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2024_parent', 'VIB', 2024, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2024_consolidated', 'VIB', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2023_consolidated', 'VIB', 2023, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2023_parent', 'VIB', 2023, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2022_consolidated', 'VIB', 2022, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2022_parent', 'VIB', 2022, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2021_parent', 'VIB', 2021, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2021_consolidated', 'VIB', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2020_consolidated', 'VIB', 2020, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2020_parent', 'VIB', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VIB_2019_parent', 'VIB', 2019, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2019_consolidated', 'VIB', 2019, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2018_consolidated', 'VIB', 2018, 'consolidated', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2017_consolidated', 'VIB', 2017, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2018_parent', 'VIB', 2018, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2017_parent', 'VIB', 2017, 'parent', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2015_consolidated', 'VIB', 2015, 'consolidated', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VIB_2016_consolidated', 'VIB', 2016, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2015_parent', 'VIB', 2015, 'parent', 'Công ty Trách nhiệm Hữu hạn Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VIB_2016_parent', 'VIB', 2016, 'parent', 'Công ty TNHH Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VHL_2025_parent', 'VHL', 2025, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2024_consolidated', 'VHL', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2025_consolidated', 'VHL', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2023_consolidated', 'VHL', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2023_parent', 'VHL', 2023, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2022_consolidated', 'VHL', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2022_parent', 'VHL', 2022, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2021_parent', 'VHL', 2021, 'parent', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2021_consolidated', 'VHL', 2021, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VHL_2020_consolidated', 'VHL', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2019_parent', 'VHL', 2019, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2019_consolidated', 'VHL', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2020_parent', 'VHL', 2020, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2018_consolidated', 'VHL', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2018_parent', 'VHL', 2018, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2015_consolidated', 'VHL', 2015, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VHL_2015_parent', 'VHL', 2015, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
