PRAGMA foreign_keys = OFF;
-- Auto-generated seed file for table: audit_reports

INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VXT_2022_consolidated', 'VXT', 2022, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VXT_2021_consolidated', 'VXT', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VXT_2022_parent', 'VXT', 2022, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('WCS_2022_consolidated', 'WCS', 2022, 'consolidated', 'AFC Vietnam Auditing Co., Ltd.', 'unqualified', 0, NULL),
('VXT_2021_parent', 'VXT', 2021, 'parent', 'AASC', 'unqualified', 0, NULL),
('VXT_2018_consolidated', 'VXT', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VXT_2020_consolidated', 'VXT', 2020, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VXT_2018_parent', 'VXT', 2018, 'parent', 'AASC', 'unqualified', 0, NULL),
('VXT_2020_parent', 'VXT', 2020, 'parent', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 0, NULL),
('VXT_2016_consolidated', 'VXT', 2016, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'qualified', 0, NULL),
('VXT_2017_consolidated', 'VXT', 2017, 'consolidated', 'AASC Auditing Firm', 'qualified', 0, NULL),
('VXT_2017_parent', 'VXT', 2017, 'parent', 'AASC Auditing Firm', 'qualified', 0, NULL),
('VXT_2016_parent', 'VXT', 2016, 'parent', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'qualified', 0, NULL),
('VXP_2025_consolidated', 'VXP', 2025, 'consolidated', 'Công ty TNHH Kiểm toán NVA', 'qualified', 0, NULL),
('VXP_2024_consolidated', 'VXP', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Định giá Việt Nam (VAE)', 'disclaimer', 1, 'Công ty lỗ 14,7 tỷ đồng năm 2024, lưu chuyển tiền thuần từ hoạt động kinh doanh âm 6,02 tỷ đồng. Khoản nợ phải trả với Boehringer Ingelheim (nhà cung cấp chính) quá hạn 17,9 tỷ đồng (724.211 USD). Khoản lãi vay phải trả Ngân hàng Phát triển Việt Nam 2,7 tỷ đồng tồn đọng nhiều năm ảnh hưởng đến chỉ số tín nhiệm. Công ty khó tiếp cận khoản vay với tổ chức tín dụng.'),
('WSB_2020_parent', 'WSB', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VXP_2022_consolidated', 'VXP', 2022, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('VXP_2019_consolidated', 'VXP', 2019, 'consolidated', 'AASCN (Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt)', 'unqualified', 0, NULL),
('VXP_2021_consolidated', 'VXP', 2021, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('VXP_2018_consolidated', 'VXP', 2018, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VXP_2017_consolidated', 'VXP', 2017, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt', 'qualified', 0, NULL),
('VXP_2016_consolidated', 'VXP', 2016, 'consolidated', 'AASCN', 'qualified', 0, NULL),
('VWS_2023_consolidated', 'VWS', 2023, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VWS_2025_consolidated', 'VWS', 2025, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VWS_2024_consolidated', 'VWS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VWS_2021_consolidated', 'VWS', 2021, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VWS_2020_consolidated', 'VWS', 2020, 'consolidated', 'CÔNG TY TNHH KIỂM TOÁN VACO', 'unqualified', 0, NULL),
('VWS_2018_consolidated', 'VWS', 2018, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VWS_2019_consolidated', 'VWS', 2019, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VWS_2017_consolidated', 'VWS', 2017, 'consolidated', 'Công ty TNHH Kiểm toán CPA Vietnam', 'unqualified', 0, NULL),
('VWS_2016_consolidated', 'VWS', 2016, 'consolidated', 'CPA Vietnam', 'unqualified', 0, NULL),
('VWS_2015_consolidated', 'VWS', 2015, 'consolidated', 'CPA VIETNAM', 'unqualified', 0, NULL),
('VW3_2024_consolidated', 'VW3', 2024, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VW3_2025_consolidated', 'VW3', 2025, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'qualified', 0, NULL),
('VW3_2022_consolidated', 'VW3', 2022, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VW3_2021_consolidated', 'VW3', 2021, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VW3_2023_consolidated', 'VW3', 2023, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VW3_2020_consolidated', 'VW3', 2020, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VVS_2025_consolidated', 'VVS', 2025, 'consolidated', 'AASC Auditing Firm Company Limited', 'unqualified', 0, NULL),
('VW3_2019_consolidated', 'VW3', 2019, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'qualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VVS_2025_parent', 'VVS', 2025, 'parent', 'AASC Auditing Firm Company Limited', 'unqualified', 0, NULL),
('VVN_2025_consolidated', 'VVN', 2025, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế INPACT', 'qualified', 1, 'Tại ngày 31/12/2025, chi phí sản xuất kinh doanh dở dang tồn đọng của các công ty con với giá trị 134,04 tỷ VND. Các công ty con vẫn đang làm việc với chủ đầu tư về thanh quyết toán. Số dư các khoản công nợ phải thu, phải trả tồn đọng lâu năm với giá trị lần lượt 139,4 tỷ VND và 198,28 tỷ VND. Kiểm toán viên chưa thu thập được đầy đủ bằng chứng để đánh giá khả năng thu hồi và nghĩa vụ nợ.'),
('VVN_2024_consolidated', 'VVN', 2024, 'consolidated', 'CPA VIETNAM', 'qualified', 0, NULL),
('VVN_2023_consolidated', 'VVN', 2023, 'consolidated', 'CPA VIETNAM', 'unqualified', 0, NULL),
('VVN_2021_parent', 'VVN', 2021, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VVN_2022_consolidated', 'VVN', 2022, 'consolidated', 'CPA VIETNAM Limited', 'qualified', 0, NULL),
('VVN_2021_consolidated', 'VVN', 2021, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 0, NULL),
('VVN_2020_parent', 'VVN', 2020, 'parent', 'Công ty TNHH Kiểm toán VACO', 'unqualified', 0, NULL),
('VVN_2020_consolidated', 'VVN', 2020, 'consolidated', 'Công ty TNHH Kiểm toán VACO', 'qualified', 0, NULL),
('VVN_2019_consolidated', 'VVN', 2019, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế Moore Global Network', 'qualified', 0, NULL),
('VXP_2023_consolidated', 'VXP', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Nhân Tâm Việt', 'unqualified', 0, NULL),
('VVN_2018_parent', 'VVN', 2018, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM - Thành viên Hãng Kiểm toán Quốc tế Moore Stephens', 'unqualified', 0, NULL),
('VVN_2019_parent', 'VVN', 2019, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VUG_2025_consolidated', 'VUG', 2025, 'consolidated', 'PwC (Vietnam) Limited', 'unqualified', 0, NULL),
('VVN_2017_parent', 'VVN', 2017, 'parent', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'unqualified', 0, NULL),
('VVN_2016_parent', 'VVN', 2016, 'parent', 'CÔNG TY TNHH KIỂM TOÁN VÀ ĐỊNH GIÁ VIỆT NAM', 'qualified', 0, 'Ý kiến kiểm toán ngoại trừ liên quan đến việc trích lập dự phòng tổn thất đầu tư tài chính dài hạn vào Công ty TNHH MTV Xi măng Quang Sơn chưa theo Thông tư 228/2009/TT-BTC và Thông tư 89/2013/TT-BTC.'),
('VUG_2025_parent', 'VUG', 2025, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2024_parent', 'VUG', 2024, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2024_consolidated', 'VUG', 2024, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2023_consolidated', 'VUG', 2023, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VUG_2023_parent', 'VUG', 2023, 'parent', 'PwC Việt Nam', 'unqualified', 0, NULL),
('VUG_2022_consolidated', 'VUG', 2022, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2022_parent', 'VUG', 2022, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2020_consolidated', 'VUG', 2020, 'consolidated', 'PwC Vietnam', 'unqualified', 0, NULL),
('VUG_2021_consolidated', 'VUG', 2021, 'consolidated', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2021_parent', 'VUG', 2021, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2019_consolidated', 'VUG', 2019, 'consolidated', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2020_parent', 'VUG', 2020, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2019_parent', 'VUG', 2019, 'parent', 'PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUG_2018_parent', 'VUG', 2018, 'parent', 'Công ty TNHH PwC (Việt Nam)', 'unqualified', 0, NULL),
('VUA_2025_consolidated', 'VUA', 2025, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VUA_2023_consolidated', 'VUA', 2023, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VUA_2021_consolidated', 'VUA', 2021, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTZ_2024_consolidated', 'VTZ', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế', 'unqualified', 0, NULL),
('VTZ_2025_consolidated', 'VTZ', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'unqualified', 0, NULL),
('VTZ_2025_parent', 'VTZ', 2025, 'parent', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'unqualified', 0, NULL),
('VTZ_2024_parent', 'VTZ', 2024, 'parent', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'unqualified', 0, NULL),
('VTZ_2023_consolidated', 'VTZ', 2023, 'consolidated', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VTZ_2022_consolidated', 'VTZ', 2022, 'consolidated', 'AASCN', 'unqualified', 0, NULL),
('VTZ_2022_parent', 'VTZ', 2022, 'parent', 'Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTX_2023_consolidated', 'VTX', 2023, 'consolidated', 'Ernst & Young Vietnam Limited', 'unqualified', 0, NULL),
('VTX_2025_consolidated', 'VTX', 2025, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 1, 'Công ty đã phát sinh lỗ thuần cho năm tài chính kết thúc ngày 31 tháng 12 năm 2025 với số tiền là 35.336.974.391 VND và tại ngày này, lỗ lũy kế của Công ty là 180.674.309.657 VND. Tại ngày 31 tháng 12 năm 2025, nợ ngắn hạn của Công ty cũng đã vượt quá tài sản ngắn hạn với số tiền là 62.937.115.394 VND. Do đó, khả năng Công ty tiếp tục duy trì hoạt động kinh doanh phụ thuộc vào khả năng hoạt động kinh doanh có lợi nhuận trong tương lai và tiếp tục nhận được sự hỗ trợ tài chính từ công ty mẹ.'),
('VTX_2024_consolidated', 'VTX', 2024, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 1, 'Công ty phát sinh lỗ thuần 104,683,866,698 VND và lỗ lũy kế 145,337,335,266 VND, nợ ngắn hạn vượt quá tài sản ngắn hạn 40,030,302,968 VND, cho thấy nghi ngờ về khả năng hoạt động liên tục. Công ty phụ thuộc vào sự hỗ trợ tài chính từ công ty mẹ là Công ty Cổ phần Kho Vận Miền Nam.'),
('VTX_2022_consolidated', 'VTX', 2022, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VTX_2017_consolidated', 'VTX', 2017, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VTX_2021_consolidated', 'VTX', 2021, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VTX_2016_consolidated', 'VTX', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Dịch vụ Tin học TP.HCM', 'unqualified', 0, NULL),
('VTX_2019_consolidated', 'VTX', 2019, 'consolidated', 'Ernst & Young Việt Nam', 'unqualified', 0, NULL),
('VTV_2025_consolidated', 'VTV', 2025, 'consolidated', '', 'unqualified', 0, NULL),
('VTX_2015_consolidated', 'VTX', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn UHY ACA (UHY ACA Ltd)', 'unqualified', 0, NULL),
('VTV_2024_consolidated', 'VTV', 2024, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTV_2023_consolidated', 'VTV', 2023, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTV_2022_consolidated', 'VTV', 2022, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTV_2020_consolidated', 'VTV', 2020, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTV_2021_consolidated', 'VTV', 2021, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTV_2017_consolidated', 'VTV', 2017, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTSS_2025_consolidated', 'VTSS', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTV_2016_consolidated', 'VTV', 2016, 'consolidated', 'Công ty TNHH Kiểm toán An Việt', 'unqualified', 0, NULL),
('VTSS_2024_consolidated', 'VTSS', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('VTSS_2023_consolidated', 'VTSS', 2023, 'consolidated', 'Công ty TNHH Kiểm toán TTP', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTSS_2021_consolidated', 'VTSS', 2021, 'consolidated', 'Chi nhánh Công ty TNHH Kiểm toán - Tư vấn Đất Việt tại Hà Nội', 'unqualified', 0, NULL),
('VTSS_2020_consolidated', 'VTSS', 2020, 'consolidated', 'Công ty TNHH Hăng Kiểm toán AASC', 'unqualified', 1, 'Lỗ lũy kế âm 43,3 tỷ đồng và hoạt động không tăng trưởng do cạnh tranh từ các công ty chứng khoán lớn, dẫn đến nghi ngờ trọng yếu về khả năng hoạt động liên tục.'),
('VTSS_2019_consolidated', 'VTSS', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Công ty đang lỗ lũy kế âm 42,13 tỷ đồng (tương đương 30,53% vốn góp của chủ sở hữu). Hoạt động kinh doanh trong năm 2019 không có sự tăng trưởng đáng kể do cạnh tranh từ các công ty chứng khoán lớn. Tuy nhiên, Ban Điều hành đang có định hướng phát triển mới: đẩy mạnh môi giới, xin cấp phép tự doanh và cho vay ký quỹ.'),
('VTSC_2025_consolidated', 'VTSC', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTSS_2015_consolidated', 'VTSS', 2015, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTSC_2023_consolidated', 'VTSC', 2023, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTSS_2017_consolidated', 'VTSS', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTSC_2024_consolidated', 'VTSC', 2024, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTSC_2020_consolidated', 'VTSC', 2020, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTSC_2019_consolidated', 'VTSC', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTSC_2017_consolidated', 'VTSC', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (A&C Auditing and Consulting Co., Ltd.)', 'unqualified', 0, NULL),
('VTSC_2021_consolidated', 'VTSC', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTSC_2018_consolidated', 'VTSC', 2018, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTSC_2016_consolidated', 'VTSC', 2016, 'consolidated', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTSC_2015_consolidated', 'VTSC', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTS_2024_consolidated', 'VTS', 2024, 'consolidated', 'AASC', 'unqualified', 1, 'Đến thời điểm 31/12/2024, lỗ lũy kế của Công ty là 36,59 tỷ VND, tương ứng 183% vốn góp của chủ sở hữu. Công ty đang tạm dùng hoạt động sản xuất tại Nhà máy Từ Sơn và đang trong quá trình thanh lý tài sản tại Nhà máy Hải Dương do đất bị thu hồi. Những sự kiện này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VTS_2025_consolidated', 'VTS', 2025, 'consolidated', 'Công ty TNHH Hằng Kiểm toán AASC', 'unqualified', 1, 'Tại ngày 31/12/2025, lỗ lũy kế của Công ty là 35,86 tỷ VND, tương ứng 179% vốn góp của chủ sở hữu, dẫn đến nghi ngờ về khả năng hoạt động liên tục.'),
('VTS_2023_consolidated', 'VTS', 2023, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 1, 'Một phần diện tích đất thuê tại Nhà máy Hải Dương đã hết thời hạn thuê và đang trong quá trình chuẩn bị bàn giao mặt bằng theo Quyết định số 2832/QĐ-UBND ngày 28/09/2021. Công ty đang tìm kiếm đối tác để thanh lý nguyên vật liệu, tài sản không có nhu cầu sử dụng tại nhà máy này.'),
('VTS_2019_consolidated', 'VTS', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTS_2021_consolidated', 'VTS', 2021, 'consolidated', 'Công ty TNHH Hăng kiểm toán AASC', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTS_2020_consolidated', 'VTS', 2020, 'consolidated', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTS_2018_consolidated', 'VTS', 2018, 'consolidated', 'AASC Auditing Firm', 'unqualified', 0, NULL),
('VTS_2017_consolidated', 'VTS', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTS_2016_consolidated', 'VTS', 2016, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VVN_2017_consolidated', 'VVN', 2017, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 0, NULL),
('VTR_2025_consolidated', 'VTR', 2025, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VTR_2023_consolidated', 'VTR', 2023, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VXP_2020_consolidated', 'VXP', 2020, 'consolidated', 'Chi nhánh Công ty TNHH Dịch vụ Tư vấn Tài chính Kế toán và Kiểm toán Nam Việt (AASCN)', 'unqualified', 0, NULL),
('VTR_2024_consolidated', 'VTR', 2024, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VTR_2021_consolidated', 'VTR', 2021, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 1, 'Năm 2021 Tập đoàn tiếp tục bị lỗ 349.637.623.016 VND, lỗ lũy kế 185.506.379.936 VND. Nợ ngắn hạn vượt tài sản ngắn hạn 37.106.741.836 VND, có thể là dấu hiệu về khả năng hoạt động kinh doanh liên tục.'),
('VTR_2022_consolidated', 'VTR', 2022, 'consolidated', 'Công ty TNHH Kiểm toán AFC Việt Nam', 'unqualified', 0, NULL),
('VTR_2020_consolidated', 'VTR', 2020, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTR_2018_consolidated', 'VTR', 2018, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTR_2018_parent', 'VTR', 2018, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTR_2019_consolidated', 'VTR', 2019, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C (Baker Tilly A&C)', 'unqualified', 0, NULL),
('VTR_2017_consolidated', 'VTR', 2017, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTR_2017_parent', 'VTR', 2017, 'parent', 'A&C Auditing and Consulting Co., Ltd.', 'unqualified', 0, NULL),
('VTR_2016_consolidated', 'VTR', 2016, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTR_2016_parent', 'VTR', 2016, 'parent', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL),
('VTR_2015_consolidated', 'VTR', 2015, 'consolidated', 'Công ty TNHH Kiểm toán và Tư vấn A&C', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTQ_2025_consolidated', 'VTQ', 2025, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2025, Nợ ngắn hạn đã vượt quá Tài sản ngắn hạn của Công ty với số tiền là 37.191.542.190 đồng (tại ngày 01/01/2025 là 34.566.641.101 đồng). Lỗ lũy kế của Công ty đến ngày 31/12/2025 là 45.079.710.124 đồng (lỗ lũy kế đến ngày 01/01/2025 là 51.434.030.126 đồng). Điều này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VTQ_2024_consolidated', 'VTQ', 2024, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2024, Nợ ngắn hạn đã vượt quá Tài sản ngắn hạn của Công ty với số tiền là 34.566.641.101 đồng (tại ngày 01/01/2024 là 47.119.868.938 đồng). Lỗ lũy kế của Công ty đến ngày 31/12/2024 là 51.434.030.126 đồng (lỗ lũy kế đến ngày 01/01/2024 là 55.401.699.363 đồng). Điều này cho thấy sự tồn tại của yếu tố không chắc chắn trọng yếu có thể dẫn đến nghi ngờ đáng kể về khả năng hoạt động liên tục của Công ty.'),
('VTQ_2022_consolidated', 'VTQ', 2022, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế', 'unqualified', 1, 'Tại ngày 31 tháng 12 năm 2022, các khoản nợ ngắn hạn của Công ty đã vượt quá tài sản ngắn hạn là 37.852.147.239 đồng. Ngoài ra, lưu chuyển tiền thuần từ hoạt động kinh doanh năm 2022 bị âm 5.797.407.644 đồng.'),
('VTQ_2023_consolidated', 'VTQ', 2023, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'qualified', 1, 'Tại ngày 31 tháng 12 năm 2023, Nợ ngắn hạn đã vượt quá Tài sản ngắn hạn của Công ty với số tiền là 47.119.868.938 đồng. Hoạt động kinh doanh năm 2023 của Công ty đang bị lỗ với số tiền là 41.428.348.283 đồng, dẫn đến lỗ lũy kế là 53.519.401.139 đồng.'),
('VTQ_2021_consolidated', 'VTQ', 2021, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế', 'unqualified', 1, 'Tổng nợ ngắn hạn vượt quá tài sản ngắn hạn 30.450.639.298 đồng và lưu chuyển tiền thuần từ hoạt động kinh doanh âm 21.406.331.524 đồng, cho thấy nghi ngờ về khả năng hoạt động liên tục.'),
('VTQ_2018_consolidated', 'VTQ', 2018, 'consolidated', 'PKF Việt Nam', 'qualified', 1, 'Tài sản ngắn hạn (42,399,569,716 VNĐ) thấp hơn nợ ngắn hạn (130,298,140,873 VNĐ) với số tiền chênh lệch là 87,898,571,157 VNĐ. Lưu chuyển tiền thuần từ hoạt động kinh doanh bị âm 20,334,875,794 VNĐ.'),
('VTQ_2019_consolidated', 'VTQ', 2019, 'consolidated', 'PKF Việt Nam', 'qualified', 1, 'Tài sản ngắn hạn là 22.623.539.897 đồng, nợ ngắn hạn là 85.257.100.305 đồng, nợ ngắn hạn vượt tài sản ngắn hạn 62.633.560.408 đồng. Lưu chuyển tiền thuần từ hoạt động kinh doanh âm 9.190.770.386 đồng.'),
('VTQ_2020_consolidated', 'VTQ', 2020, 'consolidated', 'Công ty TNHH Kiểm toán Quốc tế (iCPA)', 'qualified', 1, 'Tài sản ngắn hạn là 33.872.906.450 đồng, nợ ngắn hạn là 78.361.081.378 đồng, nợ ngắn hạn vượt tài sản ngắn hạn 44.488.174.928 đồng. Lưu chuyển tiền thuần từ hoạt động kinh doanh bị âm 10.515.730.549 đồng. Quỹ khen thưởng phúc lợi đang bị âm 3.398.849.681 đồng. Hội đồng Quản trị và Ban Giám đốc đã xây dựng phương án kinh doanh để đảm bảo khả năng thanh toán các khoản nợ đến hạn trong vòng 01 năm tới.'),
('VTP_2025_consolidated', 'VTP', 2025, 'consolidated', 'Deloitte Vietnam Audit Company Limited', 'unqualified', 0, NULL),
('VTP_2025_parent', 'VTP', 2025, 'parent', 'Công ty TNHH Kiểm toán Deloitte Việt Nam', 'unqualified', 0, NULL),
('VTP_2024_consolidated', 'VTP', 2024, 'consolidated', 'Deloitte Vietnam Audit Co., Ltd', 'unqualified', 0, NULL),
('VTP_2024_parent', 'VTP', 2024, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VTP_2023_consolidated', 'VTP', 2023, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2023_parent', 'VTP', 2023, 'parent', 'AASC', 'unqualified', 0, NULL),
('VTP_2022_parent', 'VTP', 2022, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2021_consolidated', 'VTP', 2021, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2021_parent', 'VTP', 2021, 'parent', 'AASC', 'unqualified', 0, NULL),
('VTP_2022_consolidated', 'VTP', 2022, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTP_2020_parent', 'VTP', 2020, 'parent', 'AASC', 'unqualified', 0, NULL),
('VVN_2018_consolidated', 'VVN', 2018, 'consolidated', 'Công ty TNHH Kiểm toán CPA VIETNAM', 'qualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTP_2020_consolidated', 'VTP', 2020, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTP_2019_parent', 'VTP', 2019, 'parent', 'Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2018_consolidated', 'VTP', 2018, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2018_parent', 'VTP', 2018, 'parent', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2017_consolidated', 'VTP', 2017, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2016_consolidated', 'VTP', 2016, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTP_2017_parent', 'VTP', 2017, 'parent', 'AASC', 'unqualified', 0, NULL),
('VTP_2015_consolidated', 'VTP', 2015, 'consolidated', 'AASC', 'unqualified', 0, NULL),
('VTO_2025_parent', 'VTO', 2025, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2024_consolidated', 'VTO', 2024, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2025_consolidated', 'VTO', 2025, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VTO_2024_parent', 'VTO', 2024, 'parent', 'KPMG Limited Vietnam', 'unqualified', 0, NULL),
('VTO_2023_consolidated', 'VTO', 2023, 'consolidated', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VTO_2023_parent', 'VTO', 2023, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2021_consolidated', 'VTO', 2021, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2022_consolidated', 'VTO', 2022, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2022_parent', 'VTO', 2022, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2020_consolidated', 'VTO', 2020, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2021_parent', 'VTO', 2021, 'parent', 'KPMG Vietnam', 'unqualified', 0, NULL),
('VTO_2020_parent', 'VTO', 2020, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL);
INSERT OR REPLACE INTO `audit_reports` (`id`, `ticker`, `year`, `report_type`, `auditor_name`, `audit_opinion`, `going_concern_issue`, `going_concern_detail`) VALUES
('VTO_2019_consolidated', 'VTO', 2019, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2019_parent', 'VTO', 2019, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2018_parent', 'VTO', 2018, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2018_consolidated', 'VTO', 2018, 'consolidated', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2017_consolidated', 'VTO', 2017, 'consolidated', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2017_parent', 'VTO', 2017, 'parent', 'KPMG Việt Nam', 'unqualified', 0, NULL),
('VTO_2015_consolidated', 'VTO', 2015, 'consolidated', 'Công ty TNHH Deloitte Việt Nam', 'unqualified', 0, NULL),
('VTO_2015_parent', 'VTO', 2015, 'parent', 'Deloitte Việt Nam', 'unqualified', 0, NULL),
('VTO_2016_parent', 'VTO', 2016, 'parent', 'Công ty TNHH KPMG Việt Nam', 'unqualified', 0, NULL),
('VTM_2022_consolidated', 'VTM', 2022, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VTM_2024_consolidated', 'VTM', 2024, 'consolidated', 'AFC Việt Nam - Chi nhánh Hà Thành', 'unqualified', 0, NULL),
('VTM_2025_consolidated', 'VTM', 2025, 'consolidated', 'Công ty TNHH Kiểm toán và Thẩm định giá Việt Nam', 'unqualified', 0, NULL),
('VTM_2021_consolidated', 'VTM', 2021, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VTM_2020_consolidated', 'VTM', 2020, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VTM_2019_consolidated', 'VTM', 2019, 'consolidated', 'Công ty TNHH PKF Việt Nam', 'unqualified', 0, NULL),
('VTK_2025_consolidated', 'VTK', 2025, 'consolidated', 'Công ty TNHH Kiểm toán AASC', 'unqualified', 0, NULL),
('VTM_2016_consolidated', 'VTM', 2016, 'consolidated', 'PKF Việt Nam', 'unqualified', 0, NULL),
('VTM_2017_consolidated', 'VTM', 2017, 'consolidated', 'UHY Ltd', 'unqualified', 0, NULL),
('VTP_2019_consolidated', 'VTP', 2019, 'consolidated', 'Công ty TNHH Hãng Kiểm toán AASC', 'unqualified', 0, NULL),
('VTK_2024_consolidated', 'VTK', 2024, 'consolidated', 'AASC', 'unqualified', 0, NULL);
PRAGMA foreign_keys = ON;
